"""Verse + emulator emit: escaping, profiles, feedback, generated-file lint."""
import copy
import json
import re

import pytest

from conftest import CID
from fnm.cart import REPO_ROOT
from fnm.emit import ARITH_TEXT, carts_js_source, verse_escape, verse_source
from fnm.profiles import apply_profile, render
from verse_lint import lint, string_literals

SLOT = REPO_ROOT / "maps" / "starter" / "generated" / "fnm_active_cartridge.verse"


def test_escape_specials():
    assert verse_escape('a{b}c"d\\e') == 'a\\{b\\}c\\"d\\\\e'
    assert verse_escape("{") == "\\{"
    assert verse_escape("}") == "\\}"
    assert verse_escape("what's <1> & #2 ~") == "what\\'s \\<1\\> \\& \\#2 \\~"
    assert verse_escape("a\tb\nc\rd") == "a\\tb\\nc\\rd"
    assert verse_escape("3² × 4 ÷ 2 − 1") == "3² × 4 ÷ 2 − 1"  # raw UTF-8


def test_escape_rejects_unconfirmed_controls():
    for bad in ("\x00", "\x07", "​", " "):
        with pytest.raises(ValueError):
            verse_escape("x" + bad)


def test_ascii_profile():
    assert render("3 × 4 ÷ 2 − 1", "ascii") == "3 * 4 / 2 - 1"
    assert render("a ≤ b ≥ c ≠ d √4 π", "ascii") == "a <= b >= c != d sqrt4 pi"
    assert render("3^2", "ascii") == "3^2"
    assert render("2^(1 + 1)", "ascii") == "2^(1 + 1)"


def test_unicode_profile():
    assert render("3^2", "unicode") == "3²"
    assert render("(1 + 2)^3 × 2", "unicode") == "(1 + 2)³ × 2"
    assert render("10^23", "unicode") == "10²³"
    assert render("2^(1 + 1)", "unicode") == "2^(1 + 1)"
    assert render("3 × 4", "unicode") == "3 × 4"


def _tiny_cart(baked, **title):
    b = copy.deepcopy(baked)
    b["items"] = b["items"][:3]
    b.update(title)
    return b


def test_verse_escapes_hostile_strings(baked):
    hostile = 'Br{ace}s "quoted" back\\slash'
    b = _tiny_cart(baked, title=hostile)
    b["items"][0]["explanation"] = "{x} = \"y\" \\ z"
    src = verse_source(b, "unicode")
    assert lint(src) == []
    title_line = next(l for l in src.splitlines() if l.strip().startswith("Title :="))
    assert string_literals(title_line) == [hostile]
    assert 'Br\\{ace\\}s \\"quoted\\" back\\\\slash' in title_line


def test_verse_feedback_and_profile(baked):
    src = verse_source(baked, "ascii")
    assert lint(src) == []
    assert "profile: ascii" in src.splitlines()[1]
    assert "×" not in src and "÷" not in src and "−" not in src.split("\n", 1)[1]
    item_lines = [l for l in src.splitlines() if l.strip().startswith("fnm_item{")]
    assert len(item_lines) == len(baked["items"])
    cat = baked["misconceptions"]
    for it, line in zip(baked["items"], item_lines):
        lits = string_literals(line)
        # Id, Prompt, 4 choices, 4 feedback, Explanation
        assert lits[0] == it["id"]
        assert lits[1] == render(it["prompt"], "ascii")
        fb = lits[6:10]
        for i, m in enumerate(it["misconceptions"]):
            expect = "" if m is None else ARITH_TEXT if m == "ARITH" else render(cat[m]["student"], "ascii")
            assert fb[i] == expect
        assert f"Answer := {it['answer']}," in line


def test_generated_slot_file_lints(baked):
    src = SLOT.read_text(encoding="utf-8")
    assert src.startswith("# GENERATED by fnm — do not edit\n")
    header = "\n".join(src.splitlines()[:3])
    assert CID in header and baked["version"] in header and "profile: unicode" in header
    assert lint(src) == []
    assert "\r" not in src
    assert "3^2" not in src  # unicode profile applied
    assert src.count("fnm_item{") == len(baked["items"])


def test_lint_catches_breakage():
    good = verse_source  # noqa: F841 (documentation of intent)
    assert lint('X := "a{b"') != []
    assert lint('X := "unterminated\n') != []
    assert lint("X := array{1, 2,}") != []
    assert lint("X := array{1, (2}") != []
    assert lint('X := "\\q"') != []
    assert lint("X :=\t1") != []


def test_refuses_major_mismatch(baked):
    b = _tiny_cart(baked, protocol="fnm-cart/2")
    with pytest.raises(ValueError):
        verse_source(b)


def test_carts_js():
    src = (REPO_ROOT / "emulator" / "carts.js").read_text(encoding="utf-8")
    assert src == carts_js_source()
    assert "window.FNM_CARTRIDGES = window.FNM_CARTRIDGES || {};" in src
    m = re.search(r'window\.FNM_CARTRIDGES\["' + CID + r'"\] = (\{.*?\n\});', src, re.S)
    data = json.loads(m.group(1))
    assert data["render_profile"] == "unicode"
    assert len(data["items"]) == 200
    assert all(len(it["choices"]) == 4 for it in data["items"])  # emulator is unreduced
    assert not any(re.search(r"\^\d", it["prompt"]) for it in data["items"])
    assert any("²" in it["prompt"] or "³" in it["prompt"] for it in data["items"])
    assert data["misconceptions"]["EXP_AS_MULT"]["student"].startswith("3²")


def test_apply_profile_does_not_mutate(baked):
    before = json.dumps(baked)
    apply_profile(baked, "ascii")
    assert json.dumps(baked) == before
