// GENERATED by fnm — do not edit. Rebuilt from every cartridges/*/baked.json on insert.
// toolchain: fnm/0.1.0  profile: unicode
window.FNM_CARTRIDGES = window.FNM_CARTRIDGES || {};
window.FNM_CARTRIDGES["order-of-ops-exponents"] = {
  "protocol": "fnm-cart/1",
  "id": "order-of-ops-exponents",
  "version": "1.0.0",
  "title": "Order of Operations",
  "subtitle": "Exponents & Parentheses",
  "grade": "6",
  "standards": [
    "CCSS.MATH.CONTENT.6.EE.A.1",
    "CCSS.MATH.CONTENT.5.OA.A.1"
  ],
  "seed": 20261002,
  "items_per_tier": 40,
  "tiers": [
    {
      "tier": 1,
      "name": "Warm-up",
      "description": "Two operations. Multiply or divide before you add or subtract."
    },
    {
      "tier": 2,
      "name": "Parentheses",
      "description": "Parentheses first, then the rest."
    },
    {
      "tier": 3,
      "name": "Exponents",
      "description": "Exponents come before multiplying, dividing, adding and subtracting."
    },
    {
      "tier": 4,
      "name": "Power Moves",
      "description": "Exponents and parentheses together."
    },
    {
      "tier": 5,
      "name": "Boss Level",
      "description": "Four or more steps, nested parentheses, all operations."
    }
  ],
  "misconceptions": {
    "LTR": {
      "student": "Worked left to right. Do × and ÷ before + and −.",
      "teacher": "Evaluates strictly left to right, ignoring precedence."
    },
    "ADD_FIRST": {
      "student": "Added or subtracted too early. × and ÷ come first.",
      "teacher": "Performs addition/subtraction before multiplication/division."
    },
    "IGNORE_PARENS": {
      "student": "Skipped the parentheses. Do what's inside them first.",
      "teacher": "Ignores grouping symbols and applies normal precedence to the flat expression."
    },
    "EXP_AS_MULT": {
      "student": "3² means 3 × 3, not 3 × 2.",
      "teacher": "Treats a^b as a × b."
    },
    "EXP_AFTER_MULT": {
      "student": "Exponent goes on its base only, before multiplying.",
      "teacher": "Evaluates exponents after multiplication/division, e.g. 2 × 3² as (2 × 3)²."
    },
    "M_BEFORE_D": {
      "student": "× and ÷ are a team: go left to right between them.",
      "teacher": "Reads PEMDAS literally and multiplies before dividing regardless of position."
    },
    "A_BEFORE_S": {
      "student": "+ and − are a team: go left to right between them.",
      "teacher": "Reads PEMDAS literally and adds before subtracting regardless of position."
    }
  },
  "baked_with": "fnm/0.1.0",
  "items": [
    {
      "id": "order-of-ops-exponents/t1/001",
      "tier": 1,
      "prompt": "6 + 8 × 9",
      "choices": [
        "78",
        "74",
        "126",
        "83"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "ARITH",
        "ADD_FIRST",
        "ARITH"
      ],
      "explanation": "8 × 9 = 72, then 6 + 72 = 78."
    },
    {
      "id": "order-of-ops-exponents/t1/002",
      "tier": 1,
      "prompt": "8 − 8 ÷ 8",
      "choices": [
        "0",
        "10",
        "7",
        "17"
      ],
      "answer": 2,
      "misconceptions": [
        "ADD_FIRST",
        "ARITH",
        null,
        "ARITH"
      ],
      "explanation": "8 ÷ 8 = 1, then 8 − 1 = 7."
    },
    {
      "id": "order-of-ops-exponents/t1/003",
      "tier": 1,
      "prompt": "7 + 7 × 7",
      "choices": [
        "56",
        "98",
        "61",
        "57"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "ADD_FIRST",
        "ARITH",
        "ARITH"
      ],
      "explanation": "7 × 7 = 49, then 7 + 49 = 56."
    },
    {
      "id": "order-of-ops-exponents/t1/004",
      "tier": 1,
      "prompt": "12 + 2 ÷ 2",
      "choices": [
        "16",
        "13",
        "7",
        "17"
      ],
      "answer": 1,
      "misconceptions": [
        "ARITH",
        null,
        "ADD_FIRST",
        "ARITH"
      ],
      "explanation": "2 ÷ 2 = 1, then 12 + 1 = 13."
    },
    {
      "id": "order-of-ops-exponents/t1/005",
      "tier": 1,
      "prompt": "3 + 9 × 3",
      "choices": [
        "33",
        "36",
        "31",
        "30"
      ],
      "answer": 3,
      "misconceptions": [
        "ARITH",
        "ADD_FIRST",
        "ARITH",
        null
      ],
      "explanation": "9 × 3 = 27, then 3 + 27 = 30."
    },
    {
      "id": "order-of-ops-exponents/t1/006",
      "tier": 1,
      "prompt": "99 − 10 × 9",
      "choices": [
        "801",
        "9",
        "10",
        "14"
      ],
      "answer": 1,
      "misconceptions": [
        "ADD_FIRST",
        null,
        "ARITH",
        "ARITH"
      ],
      "explanation": "10 × 9 = 90, then 99 − 90 = 9."
    },
    {
      "id": "order-of-ops-exponents/t1/007",
      "tier": 1,
      "prompt": "2 + 4 × 6",
      "choices": [
        "36",
        "22",
        "27",
        "26"
      ],
      "answer": 3,
      "misconceptions": [
        "ADD_FIRST",
        "ARITH",
        "ARITH",
        null
      ],
      "explanation": "4 × 6 = 24, then 2 + 24 = 26."
    },
    {
      "id": "order-of-ops-exponents/t1/008",
      "tier": 1,
      "prompt": "2 + 5 × 4",
      "choices": [
        "19",
        "28",
        "23",
        "22"
      ],
      "answer": 3,
      "misconceptions": [
        "ARITH",
        "ADD_FIRST",
        "ARITH",
        null
      ],
      "explanation": "5 × 4 = 20, then 2 + 20 = 22."
    },
    {
      "id": "order-of-ops-exponents/t1/009",
      "tier": 1,
      "prompt": "10 − 4 ÷ 2",
      "choices": [
        "10",
        "8",
        "11",
        "3"
      ],
      "answer": 1,
      "misconceptions": [
        "ARITH",
        null,
        "ARITH",
        "ADD_FIRST"
      ],
      "explanation": "4 ÷ 2 = 2, then 10 − 2 = 8."
    },
    {
      "id": "order-of-ops-exponents/t1/010",
      "tier": 1,
      "prompt": "21 − 5 × 4",
      "choices": [
        "2",
        "1",
        "3",
        "64"
      ],
      "answer": 1,
      "misconceptions": [
        "ARITH",
        null,
        "ARITH",
        "ADD_FIRST"
      ],
      "explanation": "5 × 4 = 20, then 21 − 20 = 1."
    },
    {
      "id": "order-of-ops-exponents/t1/011",
      "tier": 1,
      "prompt": "12 + 9 × 6",
      "choices": [
        "69",
        "66",
        "61",
        "126"
      ],
      "answer": 1,
      "misconceptions": [
        "ARITH",
        null,
        "ARITH",
        "ADD_FIRST"
      ],
      "explanation": "9 × 6 = 54, then 12 + 54 = 66."
    },
    {
      "id": "order-of-ops-exponents/t1/012",
      "tier": 1,
      "prompt": "11 + 11 × 5",
      "choices": [
        "71",
        "110",
        "70",
        "66"
      ],
      "answer": 3,
      "misconceptions": [
        "ARITH",
        "ADD_FIRST",
        "ARITH",
        null
      ],
      "explanation": "11 × 5 = 55, then 11 + 55 = 66."
    },
    {
      "id": "order-of-ops-exponents/t1/013",
      "tier": 1,
      "prompt": "7 + 5 × 4",
      "choices": [
        "29",
        "27",
        "48",
        "22"
      ],
      "answer": 1,
      "misconceptions": [
        "ARITH",
        null,
        "ADD_FIRST",
        "ARITH"
      ],
      "explanation": "5 × 4 = 20, then 7 + 20 = 27."
    },
    {
      "id": "order-of-ops-exponents/t1/014",
      "tier": 1,
      "prompt": "17 − 4 × 3",
      "choices": [
        "9",
        "15",
        "5",
        "39"
      ],
      "answer": 2,
      "misconceptions": [
        "ARITH",
        "ARITH",
        null,
        "ADD_FIRST"
      ],
      "explanation": "4 × 3 = 12, then 17 − 12 = 5."
    },
    {
      "id": "order-of-ops-exponents/t1/015",
      "tier": 1,
      "prompt": "7 + 4 × 8",
      "choices": [
        "41",
        "88",
        "38",
        "39"
      ],
      "answer": 3,
      "misconceptions": [
        "ARITH",
        "ADD_FIRST",
        "ARITH",
        null
      ],
      "explanation": "4 × 8 = 32, then 7 + 32 = 39."
    },
    {
      "id": "order-of-ops-exponents/t1/016",
      "tier": 1,
      "prompt": "11 + 10 × 5",
      "choices": [
        "58",
        "105",
        "62",
        "61"
      ],
      "answer": 3,
      "misconceptions": [
        "ARITH",
        "ADD_FIRST",
        "ARITH",
        null
      ],
      "explanation": "10 × 5 = 50, then 11 + 50 = 61."
    },
    {
      "id": "order-of-ops-exponents/t1/017",
      "tier": 1,
      "prompt": "9 + 3 × 12",
      "choices": [
        "144",
        "43",
        "45",
        "49"
      ],
      "answer": 2,
      "misconceptions": [
        "ADD_FIRST",
        "ARITH",
        null,
        "ARITH"
      ],
      "explanation": "3 × 12 = 36, then 9 + 36 = 45."
    },
    {
      "id": "order-of-ops-exponents/t1/018",
      "tier": 1,
      "prompt": "5 + 11 × 5",
      "choices": [
        "60",
        "55",
        "80",
        "64"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "ARITH",
        "ADD_FIRST",
        "ARITH"
      ],
      "explanation": "11 × 5 = 55, then 5 + 55 = 60."
    },
    {
      "id": "order-of-ops-exponents/t1/019",
      "tier": 1,
      "prompt": "40 − 3 × 12",
      "choices": [
        "4",
        "8",
        "444",
        "0"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "ARITH",
        "ADD_FIRST",
        "ARITH"
      ],
      "explanation": "3 × 12 = 36, then 40 − 36 = 4."
    },
    {
      "id": "order-of-ops-exponents/t1/020",
      "tier": 1,
      "prompt": "2 + 2 ÷ 2",
      "choices": [
        "2",
        "0",
        "3",
        "5"
      ],
      "answer": 2,
      "misconceptions": [
        "ADD_FIRST",
        "ARITH",
        null,
        "ARITH"
      ],
      "explanation": "2 ÷ 2 = 1, then 2 + 1 = 3."
    },
    {
      "id": "order-of-ops-exponents/t1/021",
      "tier": 1,
      "prompt": "8 + 7 × 7",
      "choices": [
        "62",
        "60",
        "57",
        "105"
      ],
      "answer": 2,
      "misconceptions": [
        "ARITH",
        "ARITH",
        null,
        "ADD_FIRST"
      ],
      "explanation": "7 × 7 = 49, then 8 + 49 = 57."
    },
    {
      "id": "order-of-ops-exponents/t1/022",
      "tier": 1,
      "prompt": "8 + 6 × 12",
      "choices": [
        "168",
        "70",
        "80",
        "90"
      ],
      "answer": 2,
      "misconceptions": [
        "ADD_FIRST",
        "ARITH",
        null,
        "ARITH"
      ],
      "explanation": "6 × 12 = 72, then 8 + 72 = 80."
    },
    {
      "id": "order-of-ops-exponents/t1/023",
      "tier": 1,
      "prompt": "62 − 10 × 6",
      "choices": [
        "312",
        "2",
        "5",
        "0"
      ],
      "answer": 1,
      "misconceptions": [
        "ADD_FIRST",
        null,
        "ARITH",
        "ARITH"
      ],
      "explanation": "10 × 6 = 60, then 62 − 60 = 2."
    },
    {
      "id": "order-of-ops-exponents/t1/024",
      "tier": 1,
      "prompt": "49 − 4 × 10",
      "choices": [
        "9",
        "4",
        "13",
        "450"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "ARITH",
        "ARITH",
        "ADD_FIRST"
      ],
      "explanation": "4 × 10 = 40, then 49 − 40 = 9."
    },
    {
      "id": "order-of-ops-exponents/t1/025",
      "tier": 1,
      "prompt": "12 − 6 ÷ 6",
      "choices": [
        "10",
        "1",
        "11",
        "12"
      ],
      "answer": 2,
      "misconceptions": [
        "ARITH",
        "ADD_FIRST",
        null,
        "ARITH"
      ],
      "explanation": "6 ÷ 6 = 1, then 12 − 1 = 11."
    },
    {
      "id": "order-of-ops-exponents/t1/026",
      "tier": 1,
      "prompt": "6 + 2 ÷ 2",
      "choices": [
        "7",
        "12",
        "4",
        "11"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "ARITH",
        "ADD_FIRST",
        "ARITH"
      ],
      "explanation": "2 ÷ 2 = 1, then 6 + 1 = 7."
    },
    {
      "id": "order-of-ops-exponents/t1/027",
      "tier": 1,
      "prompt": "6 + 12 ÷ 3",
      "choices": [
        "10",
        "13",
        "6",
        "12"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "ARITH",
        "ADD_FIRST",
        "ARITH"
      ],
      "explanation": "12 ÷ 3 = 4, then 6 + 4 = 10."
    },
    {
      "id": "order-of-ops-exponents/t1/028",
      "tier": 1,
      "prompt": "66 − 8 × 8",
      "choices": [
        "2",
        "0",
        "3",
        "464"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "ARITH",
        "ARITH",
        "ADD_FIRST"
      ],
      "explanation": "8 × 8 = 64, then 66 − 64 = 2."
    },
    {
      "id": "order-of-ops-exponents/t1/029",
      "tier": 1,
      "prompt": "12 − 3 ÷ 3",
      "choices": [
        "3",
        "9",
        "15",
        "11"
      ],
      "answer": 3,
      "misconceptions": [
        "ADD_FIRST",
        "ARITH",
        "ARITH",
        null
      ],
      "explanation": "3 ÷ 3 = 1, then 12 − 1 = 11."
    },
    {
      "id": "order-of-ops-exponents/t1/030",
      "tier": 1,
      "prompt": "12 + 12 × 3",
      "choices": [
        "72",
        "38",
        "58",
        "48"
      ],
      "answer": 3,
      "misconceptions": [
        "ADD_FIRST",
        "ARITH",
        "ARITH",
        null
      ],
      "explanation": "12 × 3 = 36, then 12 + 36 = 48."
    },
    {
      "id": "order-of-ops-exponents/t1/031",
      "tier": 1,
      "prompt": "48 − 4 × 10",
      "choices": [
        "8",
        "11",
        "440",
        "18"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "ARITH",
        "ADD_FIRST",
        "ARITH"
      ],
      "explanation": "4 × 10 = 40, then 48 − 40 = 8."
    },
    {
      "id": "order-of-ops-exponents/t1/032",
      "tier": 1,
      "prompt": "6 + 9 × 8",
      "choices": [
        "78",
        "68",
        "120",
        "77"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "ARITH",
        "ADD_FIRST",
        "ARITH"
      ],
      "explanation": "9 × 8 = 72, then 6 + 72 = 78."
    },
    {
      "id": "order-of-ops-exponents/t1/033",
      "tier": 1,
      "prompt": "31 − 5 × 6",
      "choices": [
        "0",
        "156",
        "3",
        "1"
      ],
      "answer": 3,
      "misconceptions": [
        "ARITH",
        "ADD_FIRST",
        "ARITH",
        null
      ],
      "explanation": "5 × 6 = 30, then 31 − 30 = 1."
    },
    {
      "id": "order-of-ops-exponents/t1/034",
      "tier": 1,
      "prompt": "7 + 4 × 10",
      "choices": [
        "52",
        "47",
        "110",
        "50"
      ],
      "answer": 1,
      "misconceptions": [
        "ARITH",
        null,
        "ADD_FIRST",
        "ARITH"
      ],
      "explanation": "4 × 10 = 40, then 7 + 40 = 47."
    },
    {
      "id": "order-of-ops-exponents/t1/035",
      "tier": 1,
      "prompt": "24 − 7 × 2",
      "choices": [
        "14",
        "34",
        "10",
        "13"
      ],
      "answer": 2,
      "misconceptions": [
        "ARITH",
        "ADD_FIRST",
        null,
        "ARITH"
      ],
      "explanation": "7 × 2 = 14, then 24 − 14 = 10."
    },
    {
      "id": "order-of-ops-exponents/t1/036",
      "tier": 1,
      "prompt": "10 + 3 × 2",
      "choices": [
        "18",
        "16",
        "11",
        "26"
      ],
      "answer": 1,
      "misconceptions": [
        "ARITH",
        null,
        "ARITH",
        "ADD_FIRST"
      ],
      "explanation": "3 × 2 = 6, then 10 + 6 = 16."
    },
    {
      "id": "order-of-ops-exponents/t1/037",
      "tier": 1,
      "prompt": "11 + 4 × 10",
      "choices": [
        "150",
        "49",
        "56",
        "51"
      ],
      "answer": 3,
      "misconceptions": [
        "ADD_FIRST",
        "ARITH",
        "ARITH",
        null
      ],
      "explanation": "4 × 10 = 40, then 11 + 40 = 51."
    },
    {
      "id": "order-of-ops-exponents/t1/038",
      "tier": 1,
      "prompt": "57 − 5 × 11",
      "choices": [
        "0",
        "7",
        "2",
        "572"
      ],
      "answer": 2,
      "misconceptions": [
        "ARITH",
        "ARITH",
        null,
        "ADD_FIRST"
      ],
      "explanation": "5 × 11 = 55, then 57 − 55 = 2."
    },
    {
      "id": "order-of-ops-exponents/t1/039",
      "tier": 1,
      "prompt": "8 − 6 ÷ 2",
      "choices": [
        "1",
        "5",
        "8",
        "4"
      ],
      "answer": 1,
      "misconceptions": [
        "ADD_FIRST",
        null,
        "ARITH",
        "ARITH"
      ],
      "explanation": "6 ÷ 2 = 3, then 8 − 3 = 5."
    },
    {
      "id": "order-of-ops-exponents/t1/040",
      "tier": 1,
      "prompt": "10 + 10 × 7",
      "choices": [
        "140",
        "90",
        "80",
        "70"
      ],
      "answer": 2,
      "misconceptions": [
        "ADD_FIRST",
        "ARITH",
        null,
        "ARITH"
      ],
      "explanation": "10 × 7 = 70, then 10 + 70 = 80."
    },
    {
      "id": "order-of-ops-exponents/t2/001",
      "tier": 2,
      "prompt": "(6 − 2) ÷ 2",
      "choices": [
        "2",
        "12",
        "5",
        "3"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "ARITH",
        "IGNORE_PARENS",
        "ARITH"
      ],
      "explanation": "6 − 2 = 4, then 4 ÷ 2 = 2."
    },
    {
      "id": "order-of-ops-exponents/t2/002",
      "tier": 2,
      "prompt": "12 × (5 + 2)",
      "choices": [
        "74",
        "62",
        "86",
        "84"
      ],
      "answer": 3,
      "misconceptions": [
        "ARITH",
        "IGNORE_PARENS",
        "ARITH",
        null
      ],
      "explanation": "5 + 2 = 7, then 12 × 7 = 84."
    },
    {
      "id": "order-of-ops-exponents/t2/003",
      "tier": 2,
      "prompt": "(7 + 8 × 10) × 10",
      "choices": [
        "807",
        "865",
        "870",
        "880"
      ],
      "answer": 2,
      "misconceptions": [
        "IGNORE_PARENS",
        "ARITH",
        null,
        "ARITH"
      ],
      "explanation": "8 × 10 = 80, then 7 + 80 = 87, then 87 × 10 = 870."
    },
    {
      "id": "order-of-ops-exponents/t2/004",
      "tier": 2,
      "prompt": "26 − (10 + 8 ÷ 2)",
      "choices": [
        "17",
        "20",
        "9",
        "12"
      ],
      "answer": 3,
      "misconceptions": [
        "ADD_FIRST",
        "IGNORE_PARENS",
        "ARITH",
        null
      ],
      "explanation": "8 ÷ 2 = 4, then 10 + 4 = 14, then 26 − 14 = 12."
    },
    {
      "id": "order-of-ops-exponents/t2/005",
      "tier": 2,
      "prompt": "5 + (11 − 9) × 10",
      "choices": [
        "23",
        "70",
        "25",
        "26"
      ],
      "answer": 2,
      "misconceptions": [
        "ARITH",
        "ADD_FIRST",
        null,
        "ARITH"
      ],
      "explanation": "11 − 9 = 2, then 2 × 10 = 20, then 5 + 20 = 25."
    },
    {
      "id": "order-of-ops-exponents/t2/006",
      "tier": 2,
      "prompt": "4 × 10 × (12 − 9)",
      "choices": [
        "471",
        "124",
        "125",
        "120"
      ],
      "answer": 3,
      "misconceptions": [
        "IGNORE_PARENS",
        "ARITH",
        "ARITH",
        null
      ],
      "explanation": "12 − 9 = 3, then 4 × 10 = 40, then 40 × 3 = 120."
    },
    {
      "id": "order-of-ops-exponents/t2/007",
      "tier": 2,
      "prompt": "60 ÷ (12 + 3)",
      "choices": [
        "2",
        "4",
        "3",
        "8"
      ],
      "answer": 1,
      "misconceptions": [
        "ARITH",
        null,
        "ARITH",
        "IGNORE_PARENS"
      ],
      "explanation": "12 + 3 = 15, then 60 ÷ 15 = 4."
    },
    {
      "id": "order-of-ops-exponents/t2/008",
      "tier": 2,
      "prompt": "(9 + 4) × 11",
      "choices": [
        "53",
        "144",
        "143",
        "133"
      ],
      "answer": 2,
      "misconceptions": [
        "IGNORE_PARENS",
        "ARITH",
        null,
        "ARITH"
      ],
      "explanation": "9 + 4 = 13, then 13 × 11 = 143."
    },
    {
      "id": "order-of-ops-exponents/t2/009",
      "tier": 2,
      "prompt": "3 − (4 − 2) + 8",
      "choices": [
        "5",
        "9",
        "11",
        "14"
      ],
      "answer": 1,
      "misconceptions": [
        "IGNORE_PARENS",
        null,
        "ARITH",
        "ARITH"
      ],
      "explanation": "4 − 2 = 2, then 3 − 2 = 1, then 1 + 8 = 9."
    },
    {
      "id": "order-of-ops-exponents/t2/010",
      "tier": 2,
      "prompt": "12 × (64 − 6 × 10)",
      "choices": [
        "708",
        "38",
        "48",
        "49"
      ],
      "answer": 2,
      "misconceptions": [
        "IGNORE_PARENS",
        "ARITH",
        null,
        "ARITH"
      ],
      "explanation": "6 × 10 = 60, then 64 − 60 = 4, then 12 × 4 = 48."
    },
    {
      "id": "order-of-ops-exponents/t2/011",
      "tier": 2,
      "prompt": "(8 + 7) × 12",
      "choices": [
        "181",
        "180",
        "92",
        "176"
      ],
      "answer": 1,
      "misconceptions": [
        "ARITH",
        null,
        "IGNORE_PARENS",
        "ARITH"
      ],
      "explanation": "8 + 7 = 15, then 15 × 12 = 180."
    },
    {
      "id": "order-of-ops-exponents/t2/012",
      "tier": 2,
      "prompt": "(3 + 9 × 8) × 8",
      "choices": [
        "600",
        "605",
        "579",
        "768"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "ARITH",
        "IGNORE_PARENS",
        "ADD_FIRST"
      ],
      "explanation": "9 × 8 = 72, then 3 + 72 = 75, then 75 × 8 = 600."
    },
    {
      "id": "order-of-ops-exponents/t2/013",
      "tier": 2,
      "prompt": "(6 + 12) ÷ 2",
      "choices": [
        "12",
        "4",
        "5",
        "9"
      ],
      "answer": 3,
      "misconceptions": [
        "IGNORE_PARENS",
        "ARITH",
        "ARITH",
        null
      ],
      "explanation": "6 + 12 = 18, then 18 ÷ 2 = 9."
    },
    {
      "id": "order-of-ops-exponents/t2/014",
      "tier": 2,
      "prompt": "7 × (12 + 10)",
      "choices": [
        "153",
        "94",
        "154",
        "159"
      ],
      "answer": 2,
      "misconceptions": [
        "ARITH",
        "IGNORE_PARENS",
        null,
        "ARITH"
      ],
      "explanation": "12 + 10 = 22, then 7 × 22 = 154."
    },
    {
      "id": "order-of-ops-exponents/t2/015",
      "tier": 2,
      "prompt": "4 × (6 − 2)",
      "choices": [
        "22",
        "19",
        "16",
        "13"
      ],
      "answer": 2,
      "misconceptions": [
        "IGNORE_PARENS",
        "ARITH",
        null,
        "ARITH"
      ],
      "explanation": "6 − 2 = 4, then 4 × 4 = 16."
    },
    {
      "id": "order-of-ops-exponents/t2/016",
      "tier": 2,
      "prompt": "6 × (71 − 5 × 12)",
      "choices": [
        "366",
        "67",
        "66",
        "69"
      ],
      "answer": 2,
      "misconceptions": [
        "IGNORE_PARENS",
        "ARITH",
        null,
        "ARITH"
      ],
      "explanation": "5 × 12 = 60, then 71 − 60 = 11, then 6 × 11 = 66."
    },
    {
      "id": "order-of-ops-exponents/t2/017",
      "tier": 2,
      "prompt": "3 × (12 − 5)",
      "choices": [
        "21",
        "22",
        "19",
        "31"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "ARITH",
        "ARITH",
        "IGNORE_PARENS"
      ],
      "explanation": "12 − 5 = 7, then 3 × 7 = 21."
    },
    {
      "id": "order-of-ops-exponents/t2/018",
      "tier": 2,
      "prompt": "(8 + 11 × 8) ÷ 8",
      "choices": [
        "12",
        "8",
        "2",
        "19"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "ARITH",
        "ARITH",
        "IGNORE_PARENS"
      ],
      "explanation": "11 × 8 = 88, then 8 + 88 = 96, then 96 ÷ 8 = 12."
    },
    {
      "id": "order-of-ops-exponents/t2/019",
      "tier": 2,
      "prompt": "15 − (2 + 10)",
      "choices": [
        "23",
        "6",
        "5",
        "3"
      ],
      "answer": 3,
      "misconceptions": [
        "IGNORE_PARENS",
        "ARITH",
        "ARITH",
        null
      ],
      "explanation": "2 + 10 = 12, then 15 − 12 = 3."
    },
    {
      "id": "order-of-ops-exponents/t2/020",
      "tier": 2,
      "prompt": "7 × (4 − 1) + 11",
      "choices": [
        "98",
        "32",
        "31",
        "38"
      ],
      "answer": 1,
      "misconceptions": [
        "ADD_FIRST",
        null,
        "ARITH",
        "IGNORE_PARENS"
      ],
      "explanation": "4 − 1 = 3, then 7 × 3 = 21, then 21 + 11 = 32."
    },
    {
      "id": "order-of-ops-exponents/t2/021",
      "tier": 2,
      "prompt": "21 − (2 + 6 + 10)",
      "choices": [
        "3",
        "35",
        "4",
        "2"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "IGNORE_PARENS",
        "ARITH",
        "ARITH"
      ],
      "explanation": "2 + 6 = 8, then 8 + 10 = 18, then 21 − 18 = 3."
    },
    {
      "id": "order-of-ops-exponents/t2/022",
      "tier": 2,
      "prompt": "(10 + 9 + 10) × 10",
      "choices": [
        "280",
        "290",
        "119",
        "288"
      ],
      "answer": 1,
      "misconceptions": [
        "ARITH",
        null,
        "IGNORE_PARENS",
        "ARITH"
      ],
      "explanation": "10 + 9 = 19, then 19 + 10 = 29, then 29 × 10 = 290."
    },
    {
      "id": "order-of-ops-exponents/t2/023",
      "tier": 2,
      "prompt": "(6 + 3) × 5",
      "choices": [
        "45",
        "42",
        "35",
        "21"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "ARITH",
        "ARITH",
        "IGNORE_PARENS"
      ],
      "explanation": "6 + 3 = 9, then 9 × 5 = 45."
    },
    {
      "id": "order-of-ops-exponents/t2/024",
      "tier": 2,
      "prompt": "8 ÷ 4 × (11 − 10)",
      "choices": [
        "1",
        "4",
        "2",
        "12"
      ],
      "answer": 2,
      "misconceptions": [
        "ARITH",
        "ARITH",
        null,
        "IGNORE_PARENS"
      ],
      "explanation": "11 − 10 = 1, then 8 ÷ 4 = 2, then 2 × 1 = 2."
    },
    {
      "id": "order-of-ops-exponents/t2/025",
      "tier": 2,
      "prompt": "7 × (3 ÷ 3 + 7)",
      "choices": [
        "66",
        "57",
        "14",
        "56"
      ],
      "answer": 3,
      "misconceptions": [
        "ARITH",
        "ARITH",
        "IGNORE_PARENS",
        null
      ],
      "explanation": "3 ÷ 3 = 1, then 1 + 7 = 8, then 7 × 8 = 56."
    },
    {
      "id": "order-of-ops-exponents/t2/026",
      "tier": 2,
      "prompt": "(7 + 5) × 10",
      "choices": [
        "119",
        "115",
        "120",
        "57"
      ],
      "answer": 2,
      "misconceptions": [
        "ARITH",
        "ARITH",
        null,
        "IGNORE_PARENS"
      ],
      "explanation": "7 + 5 = 12, then 12 × 10 = 120."
    },
    {
      "id": "order-of-ops-exponents/t2/027",
      "tier": 2,
      "prompt": "(11 + 4) × 12",
      "choices": [
        "184",
        "175",
        "59",
        "180"
      ],
      "answer": 3,
      "misconceptions": [
        "ARITH",
        "ARITH",
        "IGNORE_PARENS",
        null
      ],
      "explanation": "11 + 4 = 15, then 15 × 12 = 180."
    },
    {
      "id": "order-of-ops-exponents/t2/028",
      "tier": 2,
      "prompt": "6 + (7 − 4) ÷ 3",
      "choices": [
        "7",
        "17",
        "3",
        "6"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "ARITH",
        "ADD_FIRST",
        "ARITH"
      ],
      "explanation": "7 − 4 = 3, then 3 ÷ 3 = 1, then 6 + 1 = 7."
    },
    {
      "id": "order-of-ops-exponents/t2/029",
      "tier": 2,
      "prompt": "(5 × 4 + 5) × 3",
      "choices": [
        "135",
        "35",
        "70",
        "75"
      ],
      "answer": 3,
      "misconceptions": [
        "ADD_FIRST",
        "IGNORE_PARENS",
        "ARITH",
        null
      ],
      "explanation": "5 × 4 = 20, then 20 + 5 = 25, then 25 × 3 = 75."
    },
    {
      "id": "order-of-ops-exponents/t2/030",
      "tier": 2,
      "prompt": "24 ÷ (4 + 8)",
      "choices": [
        "14",
        "2",
        "6",
        "4"
      ],
      "answer": 1,
      "misconceptions": [
        "IGNORE_PARENS",
        null,
        "ARITH",
        "ARITH"
      ],
      "explanation": "4 + 8 = 12, then 24 ÷ 12 = 2."
    },
    {
      "id": "order-of-ops-exponents/t2/031",
      "tier": 2,
      "prompt": "6 × (12 + 12 ÷ 6)",
      "choices": [
        "74",
        "84",
        "24",
        "87"
      ],
      "answer": 1,
      "misconceptions": [
        "IGNORE_PARENS",
        null,
        "ADD_FIRST",
        "ARITH"
      ],
      "explanation": "12 ÷ 6 = 2, then 12 + 2 = 14, then 6 × 14 = 84."
    },
    {
      "id": "order-of-ops-exponents/t2/032",
      "tier": 2,
      "prompt": "7 − (4 − 10 ÷ 5)",
      "choices": [
        "5",
        "1",
        "10",
        "7"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "IGNORE_PARENS",
        "ARITH",
        "ARITH"
      ],
      "explanation": "10 ÷ 5 = 2, then 4 − 2 = 2, then 7 − 2 = 5."
    },
    {
      "id": "order-of-ops-exponents/t2/033",
      "tier": 2,
      "prompt": "40 ÷ (10 ÷ 2)",
      "choices": [
        "5",
        "2",
        "9",
        "8"
      ],
      "answer": 3,
      "misconceptions": [
        "ARITH",
        "IGNORE_PARENS",
        "ARITH",
        null
      ],
      "explanation": "10 ÷ 2 = 5, then 40 ÷ 5 = 8."
    },
    {
      "id": "order-of-ops-exponents/t2/034",
      "tier": 2,
      "prompt": "8 × 12 × (7 − 6)",
      "choices": [
        "96",
        "666",
        "99",
        "97"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "IGNORE_PARENS",
        "ARITH",
        "ARITH"
      ],
      "explanation": "7 − 6 = 1, then 8 × 12 = 96, then 96 × 1 = 96."
    },
    {
      "id": "order-of-ops-exponents/t2/035",
      "tier": 2,
      "prompt": "11 × (7 + 5)",
      "choices": [
        "82",
        "135",
        "132",
        "130"
      ],
      "answer": 2,
      "misconceptions": [
        "IGNORE_PARENS",
        "ARITH",
        null,
        "ARITH"
      ],
      "explanation": "7 + 5 = 12, then 11 × 12 = 132."
    },
    {
      "id": "order-of-ops-exponents/t2/036",
      "tier": 2,
      "prompt": "10 − 1 − (2 − 1)",
      "choices": [
        "8",
        "6",
        "10",
        "12"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "IGNORE_PARENS",
        "ARITH",
        "ARITH"
      ],
      "explanation": "2 − 1 = 1, then 10 − 1 = 9, then 9 − 1 = 8."
    },
    {
      "id": "order-of-ops-exponents/t2/037",
      "tier": 2,
      "prompt": "64 − (11 + 7 × 6)",
      "choices": [
        "95",
        "11",
        "8",
        "1"
      ],
      "answer": 1,
      "misconceptions": [
        "IGNORE_PARENS",
        null,
        "ARITH",
        "ARITH"
      ],
      "explanation": "7 × 6 = 42, then 11 + 42 = 53, then 64 − 53 = 11."
    },
    {
      "id": "order-of-ops-exponents/t2/038",
      "tier": 2,
      "prompt": "88 ÷ (11 × 2) + 5",
      "choices": [
        "14",
        "21",
        "8",
        "9"
      ],
      "answer": 3,
      "misconceptions": [
        "ARITH",
        "IGNORE_PARENS",
        "ARITH",
        null
      ],
      "explanation": "11 × 2 = 22, then 88 ÷ 22 = 4, then 4 + 5 = 9."
    },
    {
      "id": "order-of-ops-exponents/t2/039",
      "tier": 2,
      "prompt": "(4 − 1) × 3",
      "choices": [
        "1",
        "9",
        "5",
        "4"
      ],
      "answer": 1,
      "misconceptions": [
        "IGNORE_PARENS",
        null,
        "ARITH",
        "ARITH"
      ],
      "explanation": "4 − 1 = 3, then 3 × 3 = 9."
    },
    {
      "id": "order-of-ops-exponents/t2/040",
      "tier": 2,
      "prompt": "7 + 10 − (8 − 5)",
      "choices": [
        "11",
        "14",
        "19",
        "4"
      ],
      "answer": 1,
      "misconceptions": [
        "ARITH",
        null,
        "ARITH",
        "IGNORE_PARENS"
      ],
      "explanation": "8 − 5 = 3, then 7 + 10 = 17, then 17 − 3 = 14."
    },
    {
      "id": "order-of-ops-exponents/t3/001",
      "tier": 3,
      "prompt": "9 × 12 + 8²",
      "choices": [
        "168",
        "172",
        "684",
        "124"
      ],
      "answer": 1,
      "misconceptions": [
        "ARITH",
        null,
        "ADD_FIRST",
        "EXP_AS_MULT"
      ],
      "explanation": "8² = 64, then 9 × 12 = 108, then 108 + 64 = 172."
    },
    {
      "id": "order-of-ops-exponents/t3/002",
      "tier": 3,
      "prompt": "43 − 8 × 2²",
      "choices": [
        "11",
        "140",
        "9",
        "8"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "ADD_FIRST",
        "ARITH",
        "ARITH"
      ],
      "explanation": "2² = 4, then 8 × 4 = 32, then 43 − 32 = 11."
    },
    {
      "id": "order-of-ops-exponents/t3/003",
      "tier": 3,
      "prompt": "8 + 8³ + 7",
      "choices": [
        "517",
        "39",
        "526",
        "527"
      ],
      "answer": 3,
      "misconceptions": [
        "ARITH",
        "EXP_AS_MULT",
        "ARITH",
        null
      ],
      "explanation": "8³ = 512, then 8 + 512 = 520, then 520 + 7 = 527."
    },
    {
      "id": "order-of-ops-exponents/t3/004",
      "tier": 3,
      "prompt": "66 − 8²",
      "choices": [
        "50",
        "4",
        "3",
        "2"
      ],
      "answer": 3,
      "misconceptions": [
        "EXP_AS_MULT",
        "ARITH",
        "ARITH",
        null
      ],
      "explanation": "8² = 64, then 66 − 64 = 2."
    },
    {
      "id": "order-of-ops-exponents/t3/005",
      "tier": 3,
      "prompt": "6 + 8³",
      "choices": [
        "518",
        "520",
        "30",
        "513"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "ARITH",
        "EXP_AS_MULT",
        "ARITH"
      ],
      "explanation": "8³ = 512, then 6 + 512 = 518."
    },
    {
      "id": "order-of-ops-exponents/t3/006",
      "tier": 3,
      "prompt": "7 + 7³",
      "choices": [
        "347",
        "350",
        "352",
        "28"
      ],
      "answer": 1,
      "misconceptions": [
        "ARITH",
        null,
        "ARITH",
        "EXP_AS_MULT"
      ],
      "explanation": "7³ = 343, then 7 + 343 = 350."
    },
    {
      "id": "order-of-ops-exponents/t3/007",
      "tier": 3,
      "prompt": "4 × 7 − 4²",
      "choices": [
        "20",
        "11",
        "576",
        "12"
      ],
      "answer": 3,
      "misconceptions": [
        "EXP_AS_MULT",
        "ARITH",
        "LTR",
        null
      ],
      "explanation": "4² = 16, then 4 × 7 = 28, then 28 − 16 = 12."
    },
    {
      "id": "order-of-ops-exponents/t3/008",
      "tier": 3,
      "prompt": "7 + 10 × 8²",
      "choices": [
        "645",
        "643",
        "647",
        "167"
      ],
      "answer": 2,
      "misconceptions": [
        "ARITH",
        "ARITH",
        null,
        "EXP_AS_MULT"
      ],
      "explanation": "8² = 64, then 10 × 64 = 640, then 7 + 640 = 647."
    },
    {
      "id": "order-of-ops-exponents/t3/009",
      "tier": 3,
      "prompt": "17 − 3²",
      "choices": [
        "196",
        "11",
        "8",
        "10"
      ],
      "answer": 2,
      "misconceptions": [
        "LTR",
        "EXP_AS_MULT",
        null,
        "ARITH"
      ],
      "explanation": "3² = 9, then 17 − 9 = 8."
    },
    {
      "id": "order-of-ops-exponents/t3/010",
      "tier": 3,
      "prompt": "10 + 8²",
      "choices": [
        "70",
        "26",
        "74",
        "324"
      ],
      "answer": 2,
      "misconceptions": [
        "ARITH",
        "EXP_AS_MULT",
        null,
        "LTR"
      ],
      "explanation": "8² = 64, then 10 + 64 = 74."
    },
    {
      "id": "order-of-ops-exponents/t3/011",
      "tier": 3,
      "prompt": "8² − 12 ÷ 4",
      "choices": [
        "71",
        "61",
        "13",
        "60"
      ],
      "answer": 1,
      "misconceptions": [
        "ARITH",
        null,
        "EXP_AS_MULT",
        "ARITH"
      ],
      "explanation": "8² = 64, then 12 ÷ 4 = 3, then 64 − 3 = 61."
    },
    {
      "id": "order-of-ops-exponents/t3/012",
      "tier": 3,
      "prompt": "3³ × 2",
      "choices": [
        "54",
        "50",
        "729",
        "18"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "ARITH",
        "EXP_AFTER_MULT",
        "EXP_AS_MULT"
      ],
      "explanation": "3³ = 27, then 27 × 2 = 54."
    },
    {
      "id": "order-of-ops-exponents/t3/013",
      "tier": 3,
      "prompt": "2 + 6³",
      "choices": [
        "20",
        "214",
        "512",
        "218"
      ],
      "answer": 3,
      "misconceptions": [
        "EXP_AS_MULT",
        "ARITH",
        "LTR",
        null
      ],
      "explanation": "6³ = 216, then 2 + 216 = 218."
    },
    {
      "id": "order-of-ops-exponents/t3/014",
      "tier": 3,
      "prompt": "7 + 5²",
      "choices": [
        "30",
        "17",
        "32",
        "144"
      ],
      "answer": 2,
      "misconceptions": [
        "ARITH",
        "EXP_AS_MULT",
        null,
        "LTR"
      ],
      "explanation": "5² = 25, then 7 + 25 = 32."
    },
    {
      "id": "order-of-ops-exponents/t3/015",
      "tier": 3,
      "prompt": "5 + 9²",
      "choices": [
        "23",
        "86",
        "196",
        "91"
      ],
      "answer": 1,
      "misconceptions": [
        "EXP_AS_MULT",
        null,
        "LTR",
        "ARITH"
      ],
      "explanation": "9² = 81, then 5 + 81 = 86."
    },
    {
      "id": "order-of-ops-exponents/t3/016",
      "tier": 3,
      "prompt": "19 − 4²",
      "choices": [
        "11",
        "3",
        "225",
        "1"
      ],
      "answer": 1,
      "misconceptions": [
        "EXP_AS_MULT",
        null,
        "LTR",
        "ARITH"
      ],
      "explanation": "4² = 16, then 19 − 16 = 3."
    },
    {
      "id": "order-of-ops-exponents/t3/017",
      "tier": 3,
      "prompt": "4 + 9²",
      "choices": [
        "169",
        "22",
        "82",
        "85"
      ],
      "answer": 3,
      "misconceptions": [
        "LTR",
        "EXP_AS_MULT",
        "ARITH",
        null
      ],
      "explanation": "9² = 81, then 4 + 81 = 85."
    },
    {
      "id": "order-of-ops-exponents/t3/018",
      "tier": 3,
      "prompt": "6 + 4³ ÷ 4",
      "choices": [
        "9",
        "25",
        "22",
        "250"
      ],
      "answer": 2,
      "misconceptions": [
        "EXP_AS_MULT",
        "ARITH",
        null,
        "LTR"
      ],
      "explanation": "4³ = 64, then 64 ÷ 4 = 16, then 6 + 16 = 22."
    },
    {
      "id": "order-of-ops-exponents/t3/019",
      "tier": 3,
      "prompt": "7 + 6²",
      "choices": [
        "43",
        "47",
        "169",
        "19"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "ARITH",
        "LTR",
        "EXP_AS_MULT"
      ],
      "explanation": "6² = 36, then 7 + 36 = 43."
    },
    {
      "id": "order-of-ops-exponents/t3/020",
      "tier": 3,
      "prompt": "6³ × 2",
      "choices": [
        "432",
        "428",
        "36",
        "437"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "ARITH",
        "EXP_AS_MULT",
        "ARITH"
      ],
      "explanation": "6³ = 216, then 216 × 2 = 432."
    },
    {
      "id": "order-of-ops-exponents/t3/021",
      "tier": 3,
      "prompt": "9 + 9 + 7²",
      "choices": [
        "71",
        "32",
        "625",
        "67"
      ],
      "answer": 3,
      "misconceptions": [
        "ARITH",
        "EXP_AS_MULT",
        "LTR",
        null
      ],
      "explanation": "7² = 49, then 9 + 9 = 18, then 18 + 49 = 67."
    },
    {
      "id": "order-of-ops-exponents/t3/022",
      "tier": 3,
      "prompt": "10² × 2",
      "choices": [
        "200",
        "190",
        "196",
        "40"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "ARITH",
        "ARITH",
        "EXP_AS_MULT"
      ],
      "explanation": "10² = 100, then 100 × 2 = 200."
    },
    {
      "id": "order-of-ops-exponents/t3/023",
      "tier": 3,
      "prompt": "8² × 8 − 1",
      "choices": [
        "127",
        "448",
        "511",
        "510"
      ],
      "answer": 2,
      "misconceptions": [
        "EXP_AS_MULT",
        "ADD_FIRST",
        null,
        "ARITH"
      ],
      "explanation": "8² = 64, then 64 × 8 = 512, then 512 − 1 = 511."
    },
    {
      "id": "order-of-ops-exponents/t3/024",
      "tier": 3,
      "prompt": "2² × 2",
      "choices": [
        "8",
        "16",
        "4",
        "13"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "EXP_AFTER_MULT",
        "ARITH",
        "ARITH"
      ],
      "explanation": "2² = 4, then 4 × 2 = 8."
    },
    {
      "id": "order-of-ops-exponents/t3/025",
      "tier": 3,
      "prompt": "11 + 5 + 9³",
      "choices": [
        "43",
        "755",
        "745",
        "750"
      ],
      "answer": 2,
      "misconceptions": [
        "EXP_AS_MULT",
        "ARITH",
        null,
        "ARITH"
      ],
      "explanation": "9³ = 729, then 11 + 5 = 16, then 16 + 729 = 745."
    },
    {
      "id": "order-of-ops-exponents/t3/026",
      "tier": 3,
      "prompt": "87 − 5 × 4²",
      "choices": [
        "3",
        "7",
        "5",
        "47"
      ],
      "answer": 1,
      "misconceptions": [
        "ARITH",
        null,
        "ARITH",
        "EXP_AS_MULT"
      ],
      "explanation": "4² = 16, then 5 × 16 = 80, then 87 − 80 = 7."
    },
    {
      "id": "order-of-ops-exponents/t3/027",
      "tier": 3,
      "prompt": "6 + 2²",
      "choices": [
        "14",
        "64",
        "10",
        "8"
      ],
      "answer": 2,
      "misconceptions": [
        "ARITH",
        "LTR",
        null,
        "ARITH"
      ],
      "explanation": "2² = 4, then 6 + 4 = 10."
    },
    {
      "id": "order-of-ops-exponents/t3/028",
      "tier": 3,
      "prompt": "8 × 6²",
      "choices": [
        "288",
        "298",
        "96",
        "284"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "ARITH",
        "EXP_AS_MULT",
        "ARITH"
      ],
      "explanation": "6² = 36, then 8 × 36 = 288."
    },
    {
      "id": "order-of-ops-exponents/t3/029",
      "tier": 3,
      "prompt": "6 ÷ 6 + 5³",
      "choices": [
        "216",
        "125",
        "126",
        "16"
      ],
      "answer": 2,
      "misconceptions": [
        "LTR",
        "ARITH",
        null,
        "EXP_AS_MULT"
      ],
      "explanation": "5³ = 125, then 6 ÷ 6 = 1, then 1 + 125 = 126."
    },
    {
      "id": "order-of-ops-exponents/t3/030",
      "tier": 3,
      "prompt": "36 ÷ 2²",
      "choices": [
        "14",
        "9",
        "6",
        "324"
      ],
      "answer": 1,
      "misconceptions": [
        "ARITH",
        null,
        "ARITH",
        "EXP_AFTER_MULT"
      ],
      "explanation": "2² = 4, then 36 ÷ 4 = 9."
    },
    {
      "id": "order-of-ops-exponents/t3/031",
      "tier": 3,
      "prompt": "5 + 10²",
      "choices": [
        "108",
        "25",
        "105",
        "225"
      ],
      "answer": 2,
      "misconceptions": [
        "ARITH",
        "EXP_AS_MULT",
        null,
        "LTR"
      ],
      "explanation": "10² = 100, then 5 + 100 = 105."
    },
    {
      "id": "order-of-ops-exponents/t3/032",
      "tier": 3,
      "prompt": "5 − 2 + 7³",
      "choices": [
        "345",
        "347",
        "24",
        "346"
      ],
      "answer": 3,
      "misconceptions": [
        "ARITH",
        "ARITH",
        "EXP_AS_MULT",
        null
      ],
      "explanation": "7³ = 343, then 5 − 2 = 3, then 3 + 343 = 346."
    },
    {
      "id": "order-of-ops-exponents/t3/033",
      "tier": 3,
      "prompt": "54 ÷ 3²",
      "choices": [
        "324",
        "2",
        "9",
        "6"
      ],
      "answer": 3,
      "misconceptions": [
        "EXP_AFTER_MULT",
        "ARITH",
        "EXP_AS_MULT",
        null
      ],
      "explanation": "3² = 9, then 54 ÷ 9 = 6."
    },
    {
      "id": "order-of-ops-exponents/t3/034",
      "tier": 3,
      "prompt": "4² ÷ 2",
      "choices": [
        "4",
        "8",
        "9",
        "12"
      ],
      "answer": 1,
      "misconceptions": [
        "EXP_AS_MULT",
        null,
        "ARITH",
        "ARITH"
      ],
      "explanation": "4² = 16, then 16 ÷ 2 = 8."
    },
    {
      "id": "order-of-ops-exponents/t3/035",
      "tier": 3,
      "prompt": "9 + 4²",
      "choices": [
        "25",
        "23",
        "17",
        "169"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "ARITH",
        "EXP_AS_MULT",
        "LTR"
      ],
      "explanation": "4² = 16, then 9 + 16 = 25."
    },
    {
      "id": "order-of-ops-exponents/t3/036",
      "tier": 3,
      "prompt": "6² × 5 − 4",
      "choices": [
        "172",
        "176",
        "36",
        "56"
      ],
      "answer": 1,
      "misconceptions": [
        "ARITH",
        null,
        "ADD_FIRST",
        "EXP_AS_MULT"
      ],
      "explanation": "6² = 36, then 36 × 5 = 180, then 180 − 4 = 176."
    },
    {
      "id": "order-of-ops-exponents/t3/037",
      "tier": 3,
      "prompt": "4 + 5² + 6",
      "choices": [
        "32",
        "35",
        "20",
        "87"
      ],
      "answer": 1,
      "misconceptions": [
        "ARITH",
        null,
        "EXP_AS_MULT",
        "LTR"
      ],
      "explanation": "5² = 25, then 4 + 25 = 29, then 29 + 6 = 35."
    },
    {
      "id": "order-of-ops-exponents/t3/038",
      "tier": 3,
      "prompt": "8 ÷ 8 + 5³",
      "choices": [
        "126",
        "216",
        "16",
        "129"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "LTR",
        "EXP_AS_MULT",
        "ARITH"
      ],
      "explanation": "5³ = 125, then 8 ÷ 8 = 1, then 1 + 125 = 126."
    },
    {
      "id": "order-of-ops-exponents/t3/039",
      "tier": 3,
      "prompt": "3 × 6³",
      "choices": [
        "649",
        "54",
        "644",
        "648"
      ],
      "answer": 3,
      "misconceptions": [
        "ARITH",
        "EXP_AS_MULT",
        "ARITH",
        null
      ],
      "explanation": "6³ = 216, then 3 × 216 = 648."
    },
    {
      "id": "order-of-ops-exponents/t3/040",
      "tier": 3,
      "prompt": "5² ÷ 5 − 2",
      "choices": [
        "6",
        "1",
        "0",
        "3"
      ],
      "answer": 3,
      "misconceptions": [
        "ARITH",
        "ARITH",
        "EXP_AS_MULT",
        null
      ],
      "explanation": "5² = 25, then 25 ÷ 5 = 5, then 5 − 2 = 3."
    },
    {
      "id": "order-of-ops-exponents/t4/001",
      "tier": 4,
      "prompt": "11 × (9 − 5)² ÷ 8",
      "choices": [
        "18",
        "242",
        "22",
        "11"
      ],
      "answer": 2,
      "misconceptions": [
        "ARITH",
        "LTR",
        null,
        "EXP_AS_MULT"
      ],
      "explanation": "9 − 5 = 4, then 4² = 16, then 11 × 16 = 176, then 176 ÷ 8 = 22."
    },
    {
      "id": "order-of-ops-exponents/t4/002",
      "tier": 4,
      "prompt": "11 + (12 − 11) × 9²",
      "choices": [
        "92",
        "972",
        "82",
        "29"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "ADD_FIRST",
        "ARITH",
        "EXP_AS_MULT"
      ],
      "explanation": "12 − 11 = 1, then 9² = 81, then 1 × 81 = 81, then 11 + 81 = 92."
    },
    {
      "id": "order-of-ops-exponents/t4/003",
      "tier": 4,
      "prompt": "(8² + 6) ÷ 2",
      "choices": [
        "67",
        "35",
        "45",
        "11"
      ],
      "answer": 1,
      "misconceptions": [
        "IGNORE_PARENS",
        null,
        "ARITH",
        "EXP_AS_MULT"
      ],
      "explanation": "8² = 64, then 64 + 6 = 70, then 70 ÷ 2 = 35."
    },
    {
      "id": "order-of-ops-exponents/t4/004",
      "tier": 4,
      "prompt": "(10 − 4)² − 9",
      "choices": [
        "30",
        "3",
        "27",
        "28"
      ],
      "answer": 2,
      "misconceptions": [
        "ARITH",
        "EXP_AS_MULT",
        null,
        "ARITH"
      ],
      "explanation": "10 − 4 = 6, then 6² = 36, then 36 − 9 = 27."
    },
    {
      "id": "order-of-ops-exponents/t4/005",
      "tier": 4,
      "prompt": "(4 ÷ 2 + 8 ÷ 8)³",
      "choices": [
        "27",
        "26",
        "23",
        "9"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "ARITH",
        "ARITH",
        "EXP_AS_MULT"
      ],
      "explanation": "4 ÷ 2 = 2, then 8 ÷ 8 = 1, then 2 + 1 = 3, then 3³ = 27."
    },
    {
      "id": "order-of-ops-exponents/t4/006",
      "tier": 4,
      "prompt": "(6 − 2)²",
      "choices": [
        "8",
        "6",
        "16",
        "2"
      ],
      "answer": 2,
      "misconceptions": [
        "EXP_AS_MULT",
        "ARITH",
        null,
        "IGNORE_PARENS"
      ],
      "explanation": "6 − 2 = 4, then 4² = 16."
    },
    {
      "id": "order-of-ops-exponents/t4/007",
      "tier": 4,
      "prompt": "(11 × 6 ÷ 11)²",
      "choices": [
        "32",
        "37",
        "12",
        "36"
      ],
      "answer": 3,
      "misconceptions": [
        "ARITH",
        "ARITH",
        "EXP_AS_MULT",
        null
      ],
      "explanation": "11 × 6 = 66, then 66 ÷ 11 = 6, then 6² = 36."
    },
    {
      "id": "order-of-ops-exponents/t4/008",
      "tier": 4,
      "prompt": "(9 + 8 − (5 + 9))³",
      "choices": [
        "741",
        "27",
        "30",
        "9"
      ],
      "answer": 1,
      "misconceptions": [
        "IGNORE_PARENS",
        null,
        "ARITH",
        "EXP_AS_MULT"
      ],
      "explanation": "5 + 9 = 14, then 9 + 8 = 17, then 17 − 14 = 3, then 3³ = 27."
    },
    {
      "id": "order-of-ops-exponents/t4/009",
      "tier": 4,
      "prompt": "(5 − 3)² − 4 ÷ 2",
      "choices": [
        "2",
        "0",
        "6",
        "3"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "ADD_FIRST",
        "ARITH",
        "ARITH"
      ],
      "explanation": "5 − 3 = 2, then 2² = 4, then 4 ÷ 2 = 2, then 4 − 2 = 2."
    },
    {
      "id": "order-of-ops-exponents/t4/010",
      "tier": 4,
      "prompt": "(4 + 5)³",
      "choices": [
        "129",
        "27",
        "732",
        "729"
      ],
      "answer": 3,
      "misconceptions": [
        "IGNORE_PARENS",
        "EXP_AS_MULT",
        "ARITH",
        null
      ],
      "explanation": "4 + 5 = 9, then 9³ = 729."
    },
    {
      "id": "order-of-ops-exponents/t4/011",
      "tier": 4,
      "prompt": "8 × (4² − (7 − 6))",
      "choices": [
        "120",
        "115",
        "56",
        "110"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "IGNORE_PARENS",
        "EXP_AS_MULT",
        "ARITH"
      ],
      "explanation": "7 − 6 = 1, then 4² = 16, then 16 − 1 = 15, then 8 × 15 = 120."
    },
    {
      "id": "order-of-ops-exponents/t4/012",
      "tier": 4,
      "prompt": "(49 ÷ (9 − 2))² + 10",
      "choices": [
        "59",
        "60",
        "55",
        "24"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "ARITH",
        "ARITH",
        "EXP_AS_MULT"
      ],
      "explanation": "9 − 2 = 7, then 49 ÷ 7 = 7, then 7² = 49, then 49 + 10 = 59."
    },
    {
      "id": "order-of-ops-exponents/t4/013",
      "tier": 4,
      "prompt": "(5 − 2)³",
      "choices": [
        "30",
        "27",
        "23",
        "9"
      ],
      "answer": 1,
      "misconceptions": [
        "ARITH",
        null,
        "ARITH",
        "EXP_AS_MULT"
      ],
      "explanation": "5 − 2 = 3, then 3³ = 27."
    },
    {
      "id": "order-of-ops-exponents/t4/014",
      "tier": 4,
      "prompt": "(15 ÷ (4 − 1))²",
      "choices": [
        "25",
        "30",
        "22",
        "10"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "ARITH",
        "ARITH",
        "EXP_AS_MULT"
      ],
      "explanation": "4 − 1 = 3, then 15 ÷ 3 = 5, then 5² = 25."
    },
    {
      "id": "order-of-ops-exponents/t4/015",
      "tier": 4,
      "prompt": "2³ × 12 − (12 − 8)",
      "choices": [
        "76",
        "64",
        "92",
        "68"
      ],
      "answer": 2,
      "misconceptions": [
        "IGNORE_PARENS",
        "ADD_FIRST",
        null,
        "EXP_AS_MULT"
      ],
      "explanation": "12 − 8 = 4, then 2³ = 8, then 8 × 12 = 96, then 96 − 4 = 92."
    },
    {
      "id": "order-of-ops-exponents/t4/016",
      "tier": 4,
      "prompt": "(4 + (7 − 1))²",
      "choices": [
        "10",
        "20",
        "100",
        "98"
      ],
      "answer": 2,
      "misconceptions": [
        "IGNORE_PARENS",
        "EXP_AS_MULT",
        null,
        "ARITH"
      ],
      "explanation": "7 − 1 = 6, then 4 + 6 = 10, then 10² = 100."
    },
    {
      "id": "order-of-ops-exponents/t4/017",
      "tier": 4,
      "prompt": "(10 − 6)³ + 7",
      "choices": [
        "71",
        "19",
        "61",
        "70"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "EXP_AS_MULT",
        "ARITH",
        "ARITH"
      ],
      "explanation": "10 − 6 = 4, then 4³ = 64, then 64 + 7 = 71."
    },
    {
      "id": "order-of-ops-exponents/t4/018",
      "tier": 4,
      "prompt": "10 ÷ 2 × (3² + 10)",
      "choices": [
        "55",
        "95",
        "80",
        "100"
      ],
      "answer": 1,
      "misconceptions": [
        "IGNORE_PARENS",
        null,
        "EXP_AS_MULT",
        "ARITH"
      ],
      "explanation": "3² = 9, then 9 + 10 = 19, then 10 ÷ 2 = 5, then 5 × 19 = 95."
    },
    {
      "id": "order-of-ops-exponents/t4/019",
      "tier": 4,
      "prompt": "(11 − 9)³",
      "choices": [
        "5",
        "6",
        "3",
        "8"
      ],
      "answer": 3,
      "misconceptions": [
        "ARITH",
        "EXP_AS_MULT",
        "ARITH",
        null
      ],
      "explanation": "11 − 9 = 2, then 2³ = 8."
    },
    {
      "id": "order-of-ops-exponents/t4/020",
      "tier": 4,
      "prompt": "(5 ÷ 5 + 8)² + 2",
      "choices": [
        "20",
        "83",
        "80",
        "67"
      ],
      "answer": 1,
      "misconceptions": [
        "EXP_AS_MULT",
        null,
        "ARITH",
        "IGNORE_PARENS"
      ],
      "explanation": "5 ÷ 5 = 1, then 1 + 8 = 9, then 9² = 81, then 81 + 2 = 83."
    },
    {
      "id": "order-of-ops-exponents/t4/021",
      "tier": 4,
      "prompt": "(6 − 11 ÷ 11)³",
      "choices": [
        "123",
        "15",
        "122",
        "125"
      ],
      "answer": 3,
      "misconceptions": [
        "ARITH",
        "EXP_AS_MULT",
        "ARITH",
        null
      ],
      "explanation": "11 ÷ 11 = 1, then 6 − 1 = 5, then 5³ = 125."
    },
    {
      "id": "order-of-ops-exponents/t4/022",
      "tier": 4,
      "prompt": "(12 − 9)² × (3 + 12)",
      "choices": [
        "135",
        "134",
        "136",
        "90"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "ARITH",
        "ARITH",
        "EXP_AS_MULT"
      ],
      "explanation": "12 − 9 = 3, then 3 + 12 = 15, then 3² = 9, then 9 × 15 = 135."
    },
    {
      "id": "order-of-ops-exponents/t4/023",
      "tier": 4,
      "prompt": "(5 + 3 + 2 ÷ 2)²",
      "choices": [
        "18",
        "81",
        "71",
        "25"
      ],
      "answer": 1,
      "misconceptions": [
        "EXP_AS_MULT",
        null,
        "ARITH",
        "ADD_FIRST"
      ],
      "explanation": "2 ÷ 2 = 1, then 5 + 3 = 8, then 8 + 1 = 9, then 9² = 81."
    },
    {
      "id": "order-of-ops-exponents/t4/024",
      "tier": 4,
      "prompt": "(9 − 12 ÷ 2)²",
      "choices": [
        "6",
        "10",
        "9",
        "8"
      ],
      "answer": 2,
      "misconceptions": [
        "EXP_AS_MULT",
        "ARITH",
        null,
        "ARITH"
      ],
      "explanation": "12 ÷ 2 = 6, then 9 − 6 = 3, then 3² = 9."
    },
    {
      "id": "order-of-ops-exponents/t4/025",
      "tier": 4,
      "prompt": "12 + (4 − 2)²",
      "choices": [
        "196",
        "6",
        "12",
        "16"
      ],
      "answer": 3,
      "misconceptions": [
        "LTR",
        "ARITH",
        "IGNORE_PARENS",
        null
      ],
      "explanation": "4 − 2 = 2, then 2² = 4, then 12 + 4 = 16."
    },
    {
      "id": "order-of-ops-exponents/t4/026",
      "tier": 4,
      "prompt": "7² − (9 − 8)",
      "choices": [
        "32",
        "13",
        "47",
        "48"
      ],
      "answer": 3,
      "misconceptions": [
        "IGNORE_PARENS",
        "EXP_AS_MULT",
        "ARITH",
        null
      ],
      "explanation": "9 − 8 = 1, then 7² = 49, then 49 − 1 = 48."
    },
    {
      "id": "order-of-ops-exponents/t4/027",
      "tier": 4,
      "prompt": "2 + (2 + 6 − 2)²",
      "choices": [
        "38",
        "14",
        "64",
        "6"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "EXP_AS_MULT",
        "LTR",
        "IGNORE_PARENS"
      ],
      "explanation": "2 + 6 = 8, then 8 − 2 = 6, then 6² = 36, then 2 + 36 = 38."
    },
    {
      "id": "order-of-ops-exponents/t4/028",
      "tier": 4,
      "prompt": "29 − (11 − 6)² − 2",
      "choices": [
        "574",
        "17",
        "2",
        "3"
      ],
      "answer": 2,
      "misconceptions": [
        "LTR",
        "EXP_AS_MULT",
        null,
        "ARITH"
      ],
      "explanation": "11 − 6 = 5, then 5² = 25, then 29 − 25 = 4, then 4 − 2 = 2."
    },
    {
      "id": "order-of-ops-exponents/t4/029",
      "tier": 4,
      "prompt": "(23 − 4²)²",
      "choices": [
        "53",
        "46",
        "49",
        "30"
      ],
      "answer": 2,
      "misconceptions": [
        "ARITH",
        "ARITH",
        null,
        "EXP_AS_MULT"
      ],
      "explanation": "4² = 16, then 23 − 16 = 7, then 7² = 49."
    },
    {
      "id": "order-of-ops-exponents/t4/030",
      "tier": 4,
      "prompt": "7 × 4 × (46 − 6²)",
      "choices": [
        "278",
        "952",
        "281",
        "280"
      ],
      "answer": 3,
      "misconceptions": [
        "ARITH",
        "EXP_AS_MULT",
        "ARITH",
        null
      ],
      "explanation": "6² = 36, then 46 − 36 = 10, then 7 × 4 = 28, then 28 × 10 = 280."
    },
    {
      "id": "order-of-ops-exponents/t4/031",
      "tier": 4,
      "prompt": "65 − (6 + (3 − 1))²",
      "choices": [
        "4",
        "61",
        "49",
        "1"
      ],
      "answer": 3,
      "misconceptions": [
        "ARITH",
        "IGNORE_PARENS",
        "EXP_AS_MULT",
        null
      ],
      "explanation": "3 − 1 = 2, then 6 + 2 = 8, then 8² = 64, then 65 − 64 = 1."
    },
    {
      "id": "order-of-ops-exponents/t4/032",
      "tier": 4,
      "prompt": "(2 × 4)³",
      "choices": [
        "24",
        "512",
        "128",
        "517"
      ],
      "answer": 1,
      "misconceptions": [
        "EXP_AS_MULT",
        null,
        "IGNORE_PARENS",
        "ARITH"
      ],
      "explanation": "2 × 4 = 8, then 8³ = 512."
    },
    {
      "id": "order-of-ops-exponents/t4/033",
      "tier": 4,
      "prompt": "(7 ÷ 7 + 8)²",
      "choices": [
        "18",
        "85",
        "65",
        "81"
      ],
      "answer": 3,
      "misconceptions": [
        "EXP_AS_MULT",
        "ARITH",
        "IGNORE_PARENS",
        null
      ],
      "explanation": "7 ÷ 7 = 1, then 1 + 8 = 9, then 9² = 81."
    },
    {
      "id": "order-of-ops-exponents/t4/034",
      "tier": 4,
      "prompt": "(8 − (10 − 9))³",
      "choices": [
        "343",
        "348",
        "21",
        "344"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "ARITH",
        "EXP_AS_MULT",
        "ARITH"
      ],
      "explanation": "10 − 9 = 1, then 8 − 1 = 7, then 7³ = 343."
    },
    {
      "id": "order-of-ops-exponents/t4/035",
      "tier": 4,
      "prompt": "(8 × 5 ÷ 8)²",
      "choices": [
        "20",
        "23",
        "25",
        "10"
      ],
      "answer": 2,
      "misconceptions": [
        "ARITH",
        "ARITH",
        null,
        "EXP_AS_MULT"
      ],
      "explanation": "8 × 5 = 40, then 40 ÷ 8 = 5, then 5² = 25."
    },
    {
      "id": "order-of-ops-exponents/t4/036",
      "tier": 4,
      "prompt": "(6 + 3 − 2)²",
      "choices": [
        "5",
        "14",
        "49",
        "44"
      ],
      "answer": 2,
      "misconceptions": [
        "IGNORE_PARENS",
        "EXP_AS_MULT",
        null,
        "ARITH"
      ],
      "explanation": "6 + 3 = 9, then 9 − 2 = 7, then 7² = 49."
    },
    {
      "id": "order-of-ops-exponents/t4/037",
      "tier": 4,
      "prompt": "2³ − (6 − 3) + 4",
      "choices": [
        "3",
        "1",
        "7",
        "9"
      ],
      "answer": 3,
      "misconceptions": [
        "IGNORE_PARENS",
        "A_BEFORE_S",
        "EXP_AS_MULT",
        null
      ],
      "explanation": "6 − 3 = 3, then 2³ = 8, then 8 − 3 = 5, then 5 + 4 = 9."
    },
    {
      "id": "order-of-ops-exponents/t4/038",
      "tier": 4,
      "prompt": "(11 − 7)³ + 12",
      "choices": [
        "24",
        "76",
        "78",
        "72"
      ],
      "answer": 1,
      "misconceptions": [
        "EXP_AS_MULT",
        null,
        "ARITH",
        "ARITH"
      ],
      "explanation": "11 − 7 = 4, then 4³ = 64, then 64 + 12 = 76."
    },
    {
      "id": "order-of-ops-exponents/t4/039",
      "tier": 4,
      "prompt": "(9 + 4 ÷ 4)²",
      "choices": [
        "96",
        "100",
        "102",
        "20"
      ],
      "answer": 1,
      "misconceptions": [
        "ARITH",
        null,
        "ARITH",
        "EXP_AS_MULT"
      ],
      "explanation": "4 ÷ 4 = 1, then 9 + 1 = 10, then 10² = 100."
    },
    {
      "id": "order-of-ops-exponents/t4/040",
      "tier": 4,
      "prompt": "(6 − 2)³ + 10 ÷ 10",
      "choices": [
        "13",
        "65",
        "60",
        "68"
      ],
      "answer": 1,
      "misconceptions": [
        "EXP_AS_MULT",
        null,
        "ARITH",
        "ARITH"
      ],
      "explanation": "6 − 2 = 4, then 4³ = 64, then 10 ÷ 10 = 1, then 64 + 1 = 65."
    },
    {
      "id": "order-of-ops-exponents/t5/001",
      "tier": 5,
      "prompt": "(9 + 7²) ÷ 2 × 12",
      "choices": [
        "138",
        "303",
        "346",
        "348"
      ],
      "answer": 3,
      "misconceptions": [
        "EXP_AS_MULT",
        "IGNORE_PARENS",
        "ARITH",
        null
      ],
      "explanation": "7² = 49, then 9 + 49 = 58, then 58 ÷ 2 = 29, then 29 × 12 = 348."
    },
    {
      "id": "order-of-ops-exponents/t5/002",
      "tier": 5,
      "prompt": "(78 ÷ (12 ÷ 4 + 10))³",
      "choices": [
        "219",
        "18",
        "212",
        "216"
      ],
      "answer": 3,
      "misconceptions": [
        "ARITH",
        "EXP_AS_MULT",
        "ARITH",
        null
      ],
      "explanation": "12 ÷ 4 = 3, then 3 + 10 = 13, then 78 ÷ 13 = 6, then 6³ = 216."
    },
    {
      "id": "order-of-ops-exponents/t5/003",
      "tier": 5,
      "prompt": "((10 ÷ 2)² ÷ 5)²",
      "choices": [
        "22",
        "25",
        "26",
        "4"
      ],
      "answer": 1,
      "misconceptions": [
        "ARITH",
        null,
        "ARITH",
        "EXP_AS_MULT"
      ],
      "explanation": "10 ÷ 2 = 5, then 5² = 25, then 25 ÷ 5 = 5, then 5² = 25."
    },
    {
      "id": "order-of-ops-exponents/t5/004",
      "tier": 5,
      "prompt": "9³ × (10 ÷ 5 − 1)",
      "choices": [
        "739",
        "729",
        "27",
        "725"
      ],
      "answer": 1,
      "misconceptions": [
        "ARITH",
        null,
        "EXP_AS_MULT",
        "ARITH"
      ],
      "explanation": "10 ÷ 5 = 2, then 2 − 1 = 1, then 9³ = 729, then 729 × 1 = 729."
    },
    {
      "id": "order-of-ops-exponents/t5/005",
      "tier": 5,
      "prompt": "(6 × 3 − 12 + 5 ÷ 5)²",
      "choices": [
        "49",
        "45",
        "25",
        "14"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "ARITH",
        "A_BEFORE_S",
        "EXP_AS_MULT"
      ],
      "explanation": "6 × 3 = 18, then 5 ÷ 5 = 1, then 18 − 12 = 6, then 6 + 1 = 7, then 7² = 49."
    },
    {
      "id": "order-of-ops-exponents/t5/006",
      "tier": 5,
      "prompt": "(4 ÷ 2 + (12 − 10))²",
      "choices": [
        "13",
        "8",
        "1",
        "16"
      ],
      "answer": 3,
      "misconceptions": [
        "ARITH",
        "EXP_AS_MULT",
        "ADD_FIRST",
        null
      ],
      "explanation": "12 − 10 = 2, then 4 ÷ 2 = 2, then 2 + 2 = 4, then 4² = 16."
    },
    {
      "id": "order-of-ops-exponents/t5/007",
      "tier": 5,
      "prompt": "10² × (7 − 2) + 5 ÷ 5",
      "choices": [
        "101",
        "699",
        "501",
        "200"
      ],
      "answer": 2,
      "misconceptions": [
        "EXP_AS_MULT",
        "IGNORE_PARENS",
        null,
        "ADD_FIRST"
      ],
      "explanation": "7 − 2 = 5, then 10² = 100, then 100 × 5 = 500, then 5 ÷ 5 = 1, then 500 + 1 = 501."
    },
    {
      "id": "order-of-ops-exponents/t5/008",
      "tier": 5,
      "prompt": "12 × (8² + 10 + 12 ÷ 12)",
      "choices": [
        "779",
        "900",
        "324",
        "86"
      ],
      "answer": 1,
      "misconceptions": [
        "IGNORE_PARENS",
        null,
        "EXP_AS_MULT",
        "ADD_FIRST"
      ],
      "explanation": "8² = 64, then 12 ÷ 12 = 1, then 64 + 10 = 74, then 74 + 1 = 75, then 12 × 75 = 900."
    },
    {
      "id": "order-of-ops-exponents/t5/009",
      "tier": 5,
      "prompt": "8 × 7 + (8 − 4 ÷ 2)²",
      "choices": [
        "92",
        "63",
        "68",
        "88"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "IGNORE_PARENS",
        "EXP_AS_MULT",
        "ADD_FIRST"
      ],
      "explanation": "4 ÷ 2 = 2, then 8 − 2 = 6, then 6² = 36, then 8 × 7 = 56, then 56 + 36 = 92."
    },
    {
      "id": "order-of-ops-exponents/t5/010",
      "tier": 5,
      "prompt": "(4 ÷ (4 ÷ (3 − 1)))³",
      "choices": [
        "7",
        "6",
        "5",
        "8"
      ],
      "answer": 3,
      "misconceptions": [
        "ARITH",
        "EXP_AS_MULT",
        "ARITH",
        null
      ],
      "explanation": "3 − 1 = 2, then 4 ÷ 2 = 2, then 4 ÷ 2 = 2, then 2³ = 8."
    },
    {
      "id": "order-of-ops-exponents/t5/011",
      "tier": 5,
      "prompt": "(8 − 11 ÷ 11 + 2)³",
      "choices": [
        "729",
        "125",
        "27",
        "15"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "A_BEFORE_S",
        "EXP_AS_MULT",
        "IGNORE_PARENS"
      ],
      "explanation": "11 ÷ 11 = 1, then 8 − 1 = 7, then 7 + 2 = 9, then 9³ = 729."
    },
    {
      "id": "order-of-ops-exponents/t5/012",
      "tier": 5,
      "prompt": "12 × 12 × 4 + (8 ÷ 4)³",
      "choices": [
        "582",
        "580",
        "585",
        "584"
      ],
      "answer": 3,
      "misconceptions": [
        "EXP_AS_MULT",
        "ARITH",
        "ARITH",
        null
      ],
      "explanation": "8 ÷ 4 = 2, then 2³ = 8, then 12 × 12 = 144, then 144 × 4 = 576, then 576 + 8 = 584."
    },
    {
      "id": "order-of-ops-exponents/t5/013",
      "tier": 5,
      "prompt": "(8 × 2 ÷ (8 − 4))³",
      "choices": [
        "12",
        "66",
        "60",
        "64"
      ],
      "answer": 3,
      "misconceptions": [
        "EXP_AS_MULT",
        "ARITH",
        "ARITH",
        null
      ],
      "explanation": "8 − 4 = 4, then 8 × 2 = 16, then 16 ÷ 4 = 4, then 4³ = 64."
    },
    {
      "id": "order-of-ops-exponents/t5/014",
      "tier": 5,
      "prompt": "12 ÷ 3 + (10² − 2 ÷ 2)",
      "choices": [
        "53",
        "23",
        "103",
        "106"
      ],
      "answer": 2,
      "misconceptions": [
        "LTR",
        "EXP_AS_MULT",
        null,
        "ARITH"
      ],
      "explanation": "10² = 100, then 2 ÷ 2 = 1, then 100 − 1 = 99, then 12 ÷ 3 = 4, then 4 + 99 = 103."
    },
    {
      "id": "order-of-ops-exponents/t5/015",
      "tier": 5,
      "prompt": "(3³ + 12 ÷ 4) × 9",
      "choices": [
        "108",
        "54",
        "270",
        "273"
      ],
      "answer": 2,
      "misconceptions": [
        "EXP_AS_MULT",
        "IGNORE_PARENS",
        null,
        "ARITH"
      ],
      "explanation": "3³ = 27, then 12 ÷ 4 = 3, then 27 + 3 = 30, then 30 × 9 = 270."
    },
    {
      "id": "order-of-ops-exponents/t5/016",
      "tier": 5,
      "prompt": "(45 ÷ (6 − 1) + 8 − 10)³",
      "choices": [
        "343",
        "21",
        "346",
        "347"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "EXP_AS_MULT",
        "ARITH",
        "ARITH"
      ],
      "explanation": "6 − 1 = 5, then 45 ÷ 5 = 9, then 9 + 8 = 17, then 17 − 10 = 7, then 7³ = 343."
    },
    {
      "id": "order-of-ops-exponents/t5/017",
      "tier": 5,
      "prompt": "7² − ((4 + 4) ÷ 2)²",
      "choices": [
        "6",
        "33",
        "46",
        "30"
      ],
      "answer": 1,
      "misconceptions": [
        "EXP_AS_MULT",
        null,
        "IGNORE_PARENS",
        "ARITH"
      ],
      "explanation": "4 + 4 = 8, then 8 ÷ 2 = 4, then 7² = 49, then 4² = 16, then 49 − 16 = 33."
    },
    {
      "id": "order-of-ops-exponents/t5/018",
      "tier": 5,
      "prompt": "(6 × 5 + 9²) ÷ 3",
      "choices": [
        "37",
        "172",
        "57",
        "507"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "ADD_FIRST",
        "IGNORE_PARENS",
        "LTR"
      ],
      "explanation": "9² = 81, then 6 × 5 = 30, then 30 + 81 = 111, then 111 ÷ 3 = 37."
    },
    {
      "id": "order-of-ops-exponents/t5/019",
      "tier": 5,
      "prompt": "3 + (48 ÷ (4 + 2²))³",
      "choices": [
        "79",
        "21",
        "219",
        "221"
      ],
      "answer": 2,
      "misconceptions": [
        "IGNORE_PARENS",
        "EXP_AS_MULT",
        null,
        "ARITH"
      ],
      "explanation": "2² = 4, then 4 + 4 = 8, then 48 ÷ 8 = 6, then 6³ = 216, then 3 + 216 = 219."
    },
    {
      "id": "order-of-ops-exponents/t5/020",
      "tier": 5,
      "prompt": "6 ÷ 2 − 1 + (4 + 6)²",
      "choices": [
        "42",
        "144",
        "22",
        "102"
      ],
      "answer": 3,
      "misconceptions": [
        "IGNORE_PARENS",
        "LTR",
        "EXP_AS_MULT",
        null
      ],
      "explanation": "4 + 6 = 10, then 10² = 100, then 6 ÷ 2 = 3, then 3 − 1 = 2, then 2 + 100 = 102."
    },
    {
      "id": "order-of-ops-exponents/t5/021",
      "tier": 5,
      "prompt": "(3 + 7 + 10²) × (9 ÷ 3)",
      "choices": [
        "90",
        "330",
        "310",
        "325"
      ],
      "answer": 1,
      "misconceptions": [
        "EXP_AS_MULT",
        null,
        "IGNORE_PARENS",
        "ARITH"
      ],
      "explanation": "10² = 100, then 9 ÷ 3 = 3, then 3 + 7 = 10, then 10 + 100 = 110, then 110 × 3 = 330."
    },
    {
      "id": "order-of-ops-exponents/t5/022",
      "tier": 5,
      "prompt": "(6 − 4 ÷ 4) × 7²",
      "choices": [
        "250",
        "247",
        "70",
        "245"
      ],
      "answer": 3,
      "misconceptions": [
        "ARITH",
        "ARITH",
        "EXP_AS_MULT",
        null
      ],
      "explanation": "4 ÷ 4 = 1, then 6 − 1 = 5, then 7² = 49, then 5 × 49 = 245."
    },
    {
      "id": "order-of-ops-exponents/t5/023",
      "tier": 5,
      "prompt": "50 − ((9 + 5) ÷ 2)²",
      "choices": [
        "1",
        "0",
        "36",
        "2"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "ARITH",
        "EXP_AS_MULT",
        "ARITH"
      ],
      "explanation": "9 + 5 = 14, then 14 ÷ 2 = 7, then 7² = 49, then 50 − 49 = 1."
    },
    {
      "id": "order-of-ops-exponents/t5/024",
      "tier": 5,
      "prompt": "4³ × 9 × (4 ÷ 4)",
      "choices": [
        "108",
        "586",
        "576",
        "580"
      ],
      "answer": 2,
      "misconceptions": [
        "EXP_AS_MULT",
        "ARITH",
        null,
        "ARITH"
      ],
      "explanation": "4 ÷ 4 = 1, then 4³ = 64, then 64 × 9 = 576, then 576 × 1 = 576."
    },
    {
      "id": "order-of-ops-exponents/t5/025",
      "tier": 5,
      "prompt": "10 + (7 ÷ 7 + 8³ − 10)",
      "choices": [
        "729",
        "511",
        "513",
        "25"
      ],
      "answer": 2,
      "misconceptions": [
        "LTR",
        "ARITH",
        null,
        "EXP_AS_MULT"
      ],
      "explanation": "8³ = 512, then 7 ÷ 7 = 1, then 1 + 512 = 513, then 513 − 10 = 503, then 10 + 503 = 513."
    },
    {
      "id": "order-of-ops-exponents/t5/026",
      "tier": 5,
      "prompt": "(2 ÷ 2 × 4)² × (4 ÷ 2)",
      "choices": [
        "16",
        "32",
        "256",
        "36"
      ],
      "answer": 1,
      "misconceptions": [
        "EXP_AS_MULT",
        null,
        "EXP_AFTER_MULT",
        "ARITH"
      ],
      "explanation": "2 ÷ 2 = 1, then 1 × 4 = 4, then 4 ÷ 2 = 2, then 4² = 16, then 16 × 2 = 32."
    },
    {
      "id": "order-of-ops-exponents/t5/027",
      "tier": 5,
      "prompt": "(8 − 5 ÷ 5)³ + 6",
      "choices": [
        "354",
        "349",
        "27",
        "348"
      ],
      "answer": 1,
      "misconceptions": [
        "ARITH",
        null,
        "EXP_AS_MULT",
        "ARITH"
      ],
      "explanation": "5 ÷ 5 = 1, then 8 − 1 = 7, then 7³ = 343, then 343 + 6 = 349."
    },
    {
      "id": "order-of-ops-exponents/t5/028",
      "tier": 5,
      "prompt": "48 ÷ 4² × ((9 − 6) ÷ 3)",
      "choices": [
        "3",
        "144",
        "25",
        "6"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "EXP_AFTER_MULT",
        "IGNORE_PARENS",
        "EXP_AS_MULT"
      ],
      "explanation": "9 − 6 = 3, then 3 ÷ 3 = 1, then 4² = 16, then 48 ÷ 16 = 3, then 3 × 1 = 3."
    },
    {
      "id": "order-of-ops-exponents/t5/029",
      "tier": 5,
      "prompt": "(2³ ÷ (4 ÷ 2))³",
      "choices": [
        "9",
        "64",
        "65",
        "59"
      ],
      "answer": 1,
      "misconceptions": [
        "EXP_AS_MULT",
        null,
        "ARITH",
        "ARITH"
      ],
      "explanation": "4 ÷ 2 = 2, then 2³ = 8, then 8 ÷ 2 = 4, then 4³ = 64."
    },
    {
      "id": "order-of-ops-exponents/t5/030",
      "tier": 5,
      "prompt": "6 ÷ 3 × ((5 + 11) ÷ 8)³",
      "choices": [
        "64",
        "12",
        "14",
        "16"
      ],
      "answer": 3,
      "misconceptions": [
        "EXP_AFTER_MULT",
        "EXP_AS_MULT",
        "ARITH",
        null
      ],
      "explanation": "5 + 11 = 16, then 16 ÷ 8 = 2, then 2³ = 8, then 6 ÷ 3 = 2, then 2 × 8 = 16."
    },
    {
      "id": "order-of-ops-exponents/t5/031",
      "tier": 5,
      "prompt": "((2 + 5 − 2)² ÷ 5)²",
      "choices": [
        "25",
        "30",
        "4",
        "35"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "ARITH",
        "EXP_AS_MULT",
        "ARITH"
      ],
      "explanation": "2 + 5 = 7, then 7 − 2 = 5, then 5² = 25, then 25 ÷ 5 = 5, then 5² = 25."
    },
    {
      "id": "order-of-ops-exponents/t5/032",
      "tier": 5,
      "prompt": "(15 ÷ (10 − (11 − 6)))³",
      "choices": [
        "9",
        "25",
        "27",
        "24"
      ],
      "answer": 2,
      "misconceptions": [
        "EXP_AS_MULT",
        "ARITH",
        null,
        "ARITH"
      ],
      "explanation": "11 − 6 = 5, then 10 − 5 = 5, then 15 ÷ 5 = 3, then 3³ = 27."
    },
    {
      "id": "order-of-ops-exponents/t5/033",
      "tier": 5,
      "prompt": "7 ÷ 7 × 2³ × (12 + 11)",
      "choices": [
        "138",
        "107",
        "184",
        "194"
      ],
      "answer": 2,
      "misconceptions": [
        "EXP_AS_MULT",
        "IGNORE_PARENS",
        null,
        "ARITH"
      ],
      "explanation": "12 + 11 = 23, then 2³ = 8, then 7 ÷ 7 = 1, then 1 × 8 = 8, then 8 × 23 = 184."
    },
    {
      "id": "order-of-ops-exponents/t5/034",
      "tier": 5,
      "prompt": "(94 − (9 ÷ 3 + 8) × 8)²",
      "choices": [
        "603",
        "36",
        "12",
        "35"
      ],
      "answer": 1,
      "misconceptions": [
        "IGNORE_PARENS",
        null,
        "EXP_AS_MULT",
        "ARITH"
      ],
      "explanation": "9 ÷ 3 = 3, then 3 + 8 = 11, then 11 × 8 = 88, then 94 − 88 = 6, then 6² = 36."
    },
    {
      "id": "order-of-ops-exponents/t5/035",
      "tier": 5,
      "prompt": "(10² − 9 ÷ 3) × 3",
      "choices": [
        "291",
        "51",
        "91",
        "287"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "EXP_AS_MULT",
        "IGNORE_PARENS",
        "ARITH"
      ],
      "explanation": "10² = 100, then 9 ÷ 3 = 3, then 100 − 3 = 97, then 97 × 3 = 291."
    },
    {
      "id": "order-of-ops-exponents/t5/036",
      "tier": 5,
      "prompt": "(7² + 11 ÷ 11) ÷ 5",
      "choices": [
        "3",
        "10",
        "5",
        "11"
      ],
      "answer": 1,
      "misconceptions": [
        "EXP_AS_MULT",
        null,
        "ARITH",
        "ARITH"
      ],
      "explanation": "7² = 49, then 11 ÷ 11 = 1, then 49 + 1 = 50, then 50 ÷ 5 = 10."
    },
    {
      "id": "order-of-ops-exponents/t5/037",
      "tier": 5,
      "prompt": "41 − ((18 ÷ (10 − 7))² + 3)",
      "choices": [
        "12",
        "26",
        "2",
        "0"
      ],
      "answer": 2,
      "misconceptions": [
        "ARITH",
        "EXP_AS_MULT",
        null,
        "ARITH"
      ],
      "explanation": "10 − 7 = 3, then 18 ÷ 3 = 6, then 6² = 36, then 36 + 3 = 39, then 41 − 39 = 2."
    },
    {
      "id": "order-of-ops-exponents/t5/038",
      "tier": 5,
      "prompt": "(9 ÷ 3)² − 2 + (8 + 5)",
      "choices": [
        "20",
        "30",
        "12",
        "17"
      ],
      "answer": 0,
      "misconceptions": [
        null,
        "ARITH",
        "IGNORE_PARENS",
        "EXP_AS_MULT"
      ],
      "explanation": "9 ÷ 3 = 3, then 8 + 5 = 13, then 3² = 9, then 9 − 2 = 7, then 7 + 13 = 20."
    },
    {
      "id": "order-of-ops-exponents/t5/039",
      "tier": 5,
      "prompt": "(12 − 4) × (72 ÷ 6²)",
      "choices": [
        "48",
        "13",
        "4",
        "16"
      ],
      "answer": 3,
      "misconceptions": [
        "EXP_AS_MULT",
        "ARITH",
        "IGNORE_PARENS",
        null
      ],
      "explanation": "6² = 36, then 72 ÷ 36 = 2, then 12 − 4 = 8, then 8 × 2 = 16."
    },
    {
      "id": "order-of-ops-exponents/t5/040",
      "tier": 5,
      "prompt": "(12 ÷ 4 + (4 − 3))²",
      "choices": [
        "13",
        "21",
        "16",
        "8"
      ],
      "answer": 2,
      "misconceptions": [
        "ARITH",
        "ARITH",
        null,
        "EXP_AS_MULT"
      ],
      "explanation": "4 − 3 = 1, then 12 ÷ 4 = 3, then 3 + 1 = 4, then 4² = 16."
    }
  ],
  "render_profile": "unicode"
};
