"""Emitters (PROTOCOL §7): Verse cartridge slot and emulator carts.js."""
from __future__ import annotations

import json
import unicodedata
from pathlib import Path

from fnm import PROTOCOL_MAJOR, TOOLCHAIN
from fnm.cart import REPO_ROOT, cart_dir, list_ids, load_baked
from fnm.maps import (SLOT_DIR, SLOT_TXT, SLOT_VERSE, list_map_ids, load_map, maps_dir,
                      reduce_item, validate_all_maps)
from fnm.profiles import apply_profile
from fnm.validate import protocol_major

ARITH_TEXT = "Check your arithmetic."
CARTS_JS = Path("emulator") / "carts.js"

# Verse string-literal escapes. Source: The Book of Verse (Epic Games, linked from
# dev.epicgames.com "Verse Language Book of Verse Reference"), docs/01_expressions.md
# "Character literals" table and docs/02_primitives.md "Character escape sequences" table, and
# its conformance test Tests/Literals/String.versetest which asserts each escape equals the raw
# code point. Mandatory: { } (interpolation delimiters; raw braces are a syntax error), " and \.
# Also escaped (confirmed valid escapes, raw would be legal too): ' < > & # ~, and \t \n \r.
# Any other control / format character has no confirmed escape and is rejected. Non-ASCII
# printable characters are written raw in UTF-8 (the conformance tests contain raw UTF-8
# literals such as "Sarah (שרה)").
VERSE_ESCAPES = {
    "\\": "\\\\", '"': '\\"', "{": "\\{", "}": "\\}",
    "'": "\\'", "<": "\\<", ">": "\\>", "&": "\\&", "#": "\\#", "~": "\\~",
    "\t": "\\t", "\n": "\\n", "\r": "\\r",
}


def verse_escape(s: str) -> str:
    out = []
    for c in s:
        if c in VERSE_ESCAPES:
            out.append(VERSE_ESCAPES[c])
        elif unicodedata.category(c) in ("Cc", "Cf", "Cs", "Co", "Cn", "Zl", "Zp"):
            raise ValueError(f"character U+{ord(c):04X} has no confirmed Verse escape: {s!r}")
        else:
            out.append(c)
    return "".join(out)


def vstr(s: str) -> str:
    return '"' + verse_escape(s) + '"'


def varr(values) -> str:
    return "array{" + ", ".join(values) + "}"


def _check_major(baked: dict):
    if protocol_major(baked.get("protocol")) != PROTOCOL_MAJOR:
        raise ValueError(f"{baked.get('id')}: protocol {baked.get('protocol')!r} does not match "
                         f"toolchain major fnm-cart/{PROTOCOL_MAJOR}; refusing to emit")


def feedback(item: dict, catalog: dict) -> list:
    out = []
    for i, m in enumerate(item["misconceptions"]):
        if i == item["answer"]:
            out.append("")
        elif m == "ARITH":
            out.append(ARITH_TEXT)
        else:
            out.append(catalog[m]["student"])
    return out


def verse_source(baked: dict, profile: str = "unicode", max_choices: int = 4,
                 map_id: str | None = None) -> str:
    _check_major(baked)
    b = apply_profile(baked, profile)
    b["items"] = [reduce_item(it, max_choices) for it in b["items"]]
    cat = b.get("misconceptions") or {}
    lines = [
        "# GENERATED by fnm \u2014 do not edit",
        f"# cartridge: {baked['id']}  version: {baked['version']}  profile: {profile}",
        f"# map: {map_id or '-'}  max_choices: {max_choices}  protocol: {baked['protocol']}  "
        f"toolchain: {TOOLCHAIN}  items: {len(b['items'])}",
        f"# Regenerate with: python -m fnm insert {baked['id']}   (see PROTOCOL.md section 7)",
        "",
        "FnmActiveCartridge():fnm_cartridge = fnm_cartridge{",
        f"    Protocol := {vstr(b['protocol'])},",
        f"    Id := {vstr(b['id'])},",
        f"    Version := {vstr(b['version'])},",
        f"    Title := {vstr(b['title'])},",
        f"    Subtitle := {vstr(b['subtitle'])},",
        "    Tiers := array{",
    ]
    tiers = b["tiers"]
    for i, t in enumerate(tiers):
        sep = "," if i < len(tiers) - 1 else ""
        lines.append(f"        fnm_tier{{Tier := {int(t['tier'])}, Name := {vstr(t['name'])}, "
                     f"Description := {vstr(t['description'])}}}{sep}")
    lines.append("    },")
    lines.append("    Items := array{")
    items = b["items"]
    for i, it in enumerate(items):
        sep = "," if i < len(items) - 1 else ""
        lines.append(
            f"        fnm_item{{Id := {vstr(it['id'])}, Tier := {int(it['tier'])}, "
            f"Prompt := {vstr(it['prompt'])}, "
            f"Choices := {varr(vstr(c) for c in it['choices'])}, "
            f"Answer := {int(it['answer'])}, "
            f"Feedback := {varr(vstr(f) for f in feedback(it, cat))}, "
            f"Explanation := {vstr(it['explanation'])}}}{sep}")
    lines.append("    }")
    lines.append("}")
    return "\n".join(lines) + "\n"


def emit_maps(cid: str, root: Path | None = None, profile_override: str | None = None) -> list:
    """Write every registered map's slot (PROTOCOL 6a). Returns [(map_id, verse_path, profile)]."""
    bad = validate_all_maps(root)
    if bad:
        raise ValueError("invalid map profile(s): " + "; ".join(
            f"{mid}: {', '.join(f)}" for mid, f in bad.items()))
    baked = load_baked(cid, root)
    out = []
    for mid in list_map_ids(root):
        m = load_map(mid, root)
        profile = profile_override or m["render_profile"]
        src = verse_source(baked, profile, m["max_choices"], mid)
        d = maps_dir(root) / mid / SLOT_DIR
        d.mkdir(parents=True, exist_ok=True)
        (d / SLOT_VERSE).write_bytes(src.encode("utf-8"))
        slot = (f"# GENERATED by fnm - which cartridge this map holds\n"
                f"id={baked['id']}\nversion={baked['version']}\nprofile={profile}\n")
        (d / SLOT_TXT).write_bytes(slot.encode("utf-8"))
        out.append((mid, d / SLOT_VERSE, profile))
    return out


def carts_js_source(root: Path | None = None) -> str:
    lines = [
        "// GENERATED by fnm \u2014 do not edit. Rebuilt from every cartridges/*/baked.json on insert.",
        f"// toolchain: {TOOLCHAIN}  profile: unicode",
        "window.FNM_CARTRIDGES = window.FNM_CARTRIDGES || {};",
    ]
    for cid in list_ids(root):
        if not (cart_dir(cid, root) / "baked.json").exists():
            continue
        baked = load_baked(cid, root)
        _check_major(baked)
        data = json.dumps(apply_profile(baked, "unicode"), ensure_ascii=False, indent=2)
        data = data.replace("\u2028", "\\u2028").replace("\u2029", "\\u2029")
        lines.append(f"window.FNM_CARTRIDGES[{json.dumps(cid)}] = {data};")
    return "\n".join(lines) + "\n"


def emit_js(root: Path | None = None) -> Path:
    out = Path(root or REPO_ROOT) / CARTS_JS
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_bytes(carts_js_source(root).encode("utf-8"))
    return out
