"""Map profiles (PROTOCOL §6a): registry, validation, choice reduction, sync."""
from __future__ import annotations

import json
import shutil
from pathlib import Path

from fnm import PROTOCOL_MAJOR
from fnm.cart import ID_RE, REPO_ROOT
from fnm.profiles import PROFILES

SLOT_DIR = "generated"
SLOT_VERSE = "fnm_active_cartridge.verse"
SLOT_TXT = "SLOT.txt"
PROFILE_VERSE = "fnm_map_profile.verse"

# Wrong-door penalties a map may list in map.json "penalties" (each wrong answer draws one at random).
# Must match the fnm_penalty enum in console/verse/fnm_penalties.verse (a test checks). Omitted = all.
PENALTIES = ("Freeze", "Yeet", "Spike", "Mud", "Dizzy", "Blackout")

# UEFN 42.30 layout (verified 2026-10-03 by writing a file through UEFN MCP and finding it on disk):
# a project's Verse root is <project>/Content/. All files land flat in that one folder on purpose: a
# subfolder is a separate Verse module and its definitions are <internal> to it (PROTOCOL O3).
UEFN_VERSE_SUBPATH = "Content"


def maps_dir(root: Path | None = None) -> Path:
    return Path(root or REPO_ROOT) / "maps"


def list_map_ids(root: Path | None = None) -> list:
    base = maps_dir(root)
    if not base.exists():
        return []
    return sorted(p.name for p in base.iterdir() if (p / "map.json").exists())


def load_map(mid: str, root: Path | None = None) -> dict:
    with open(maps_dir(root) / mid / "map.json", encoding="utf-8") as f:
        return json.load(f)


def validate_map(m: dict, dir_name: str | None = None) -> list:
    """List of human-readable failures for one map profile."""
    from fnm.validate import protocol_major
    F = []
    if protocol_major(m.get("protocol")) != PROTOCOL_MAJOR:
        F.append(f"protocol {m.get('protocol')!r} is not fnm-cart/{PROTOCOL_MAJOR}")
    mid = m.get("id")
    if not isinstance(mid, str) or not ID_RE.match(mid):
        F.append(f"id {mid!r} must be lowercase kebab-case")
    if dir_name is not None and mid != dir_name:
        F.append(f"id {mid!r} does not match directory {dir_name!r}")
    mc = m.get("max_choices")
    if not isinstance(mc, int) or isinstance(mc, bool) or not 2 <= mc <= 4:
        F.append(f"max_choices {mc!r} must be an integer 2-4")
    if m.get("render_profile") not in PROFILES:
        F.append(f"render_profile {m.get('render_profile')!r} must be one of {list(PROFILES)}")
    up = m.get("uefn_project")
    if up is not None and (not isinstance(up, str) or not Path(up).is_absolute()):
        F.append(f"uefn_project {up!r} must be null or an absolute path")
    if not isinstance(m.get("title", ""), str):
        F.append("title must be a string")
    pen = m.get("penalties", list(PENALTIES))
    if (not isinstance(pen, list) or not pen or len(set(pen)) != len(pen)
            or any(p not in PENALTIES for p in pen)):
        F.append(f"penalties {pen!r} must be a non-empty list of distinct names from {list(PENALTIES)}")
    return F


def profile_source(m: dict) -> str:
    """The map's own Verse slot: the settings the director reads from map.json (the penalty pool)."""
    pen = m.get("penalties", list(PENALTIES))
    return "\n".join([
        "# GENERATED by fnm — do not edit",
        f"# map: {m['id']}  from maps/{m['id']}/map.json   Regenerate with: python -m fnm sync {m['id']}",
        "",
        "# Wrong-door penalties this map draws from, one at random per wrong answer.",
        "FnmMapPenalties():[]fnm_penalty = array{" + ", ".join(f"fnm_penalty.{p}" for p in pen) + "}",
        "",
    ])


def write_profile(mid: str, root: Path | None = None) -> Path:
    m = load_map(mid, root)
    d = maps_dir(root) / mid / SLOT_DIR
    d.mkdir(parents=True, exist_ok=True)
    out = d / PROFILE_VERSE
    out.write_bytes(profile_source(m).encode("utf-8"))
    return out


def validate_all_maps(root: Path | None = None) -> dict:
    """{map_id: [failures]} for every registered map with at least one failure."""
    out = {}
    for mid in list_map_ids(root):
        try:
            f = validate_map(load_map(mid, root), mid)
        except json.JSONDecodeError as e:
            f = [f"map.json is not valid JSON: {e}"]
        if f:
            out[mid] = f
    return out


def reduce_item(item: dict, max_choices: int) -> dict:
    """§6a: keep the correct choice; drop ARITH (last first), then misconceptions (last first)
    until len(choices) <= max_choices. Keeps baked relative order; re-indexes answer."""
    n = len(item["choices"])
    if n <= max_choices:
        return dict(item)
    mis, ans = item["misconceptions"], item["answer"]
    arith = [i for i in range(n) if i != ans and mis[i] == "ARITH"]
    other = [i for i in range(n) if i != ans and mis[i] != "ARITH"]
    drop_order = arith[::-1] + other[::-1]
    dropped = set(drop_order[: n - max_choices])
    keep = [i for i in range(n) if i not in dropped]
    out = dict(item)
    out["choices"] = [item["choices"][i] for i in keep]
    out["misconceptions"] = [mis[i] for i in keep]
    out["answer"] = keep.index(ans)
    return out


def read_slot(mid: str, root: Path | None = None) -> dict | None:
    """{"cartridges": [{"id", "version"}, ...] in picker order, "profile": str}, or None if never emitted."""
    p = maps_dir(root) / mid / SLOT_DIR / SLOT_TXT
    if not p.exists():
        return None
    out: dict = {"cartridges": [], "profile": None}
    for line in p.read_text(encoding="utf-8").splitlines():
        if "=" not in line or line.startswith("#"):
            continue
        k, v = (s.strip() for s in line.split("=", 1))
        if k == "cartridge":
            cid, _, version = v.partition(" ")
            out["cartridges"].append({"id": cid, "version": version})
        else:
            out[k] = v
    return out


def sync(mid: str, root: Path | None = None) -> list | None:
    """Copy console/verse/*.verse + the map's slot into the UEFN project. None if no project set."""
    root = Path(root or REPO_ROOT)
    m = load_map(mid, root)
    fails = validate_map(m, mid)
    if fails:
        raise ValueError(f"map {mid}: " + "; ".join(fails))
    proj = m.get("uefn_project")
    if proj is None:
        return None
    proj = Path(proj)
    if not proj.is_dir():
        raise FileNotFoundError(f"uefn_project {proj} does not exist")
    slot = maps_dir(root) / mid / SLOT_DIR / SLOT_VERSE
    if not slot.exists():
        raise FileNotFoundError(f"{slot} missing: run insert first")
    profile = write_profile(mid, root)
    dest = proj / UEFN_VERSE_SUBPATH.format(project=proj.name)
    dest.mkdir(parents=True, exist_ok=True)
    copied = []
    for src in sorted((root / "console" / "verse").glob("*.verse")) + [slot, profile]:
        shutil.copyfile(src, dest / src.name)
        copied.append(dest / src.name)
    return copied
